"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _EventImportance:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EventImportanceEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EventImportance.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    EVENT_IMPORTANCE_UNSPECIFIED: _EventImportance.ValueType  # 0
    EVENT_IMPORTANCE_PRODUCTION_CRITICAL: _EventImportance.ValueType  # 1
    EVENT_IMPORTANCE_PRODUCTION_STANDARD: _EventImportance.ValueType  # 2
    EVENT_IMPORTANCE_INFO: _EventImportance.ValueType  # 3
    EVENT_IMPORTANCE_DEBUG: _EventImportance.ValueType  # 4

class EventImportance(_EventImportance, metaclass=_EventImportanceEnumTypeWrapper): ...

EVENT_IMPORTANCE_UNSPECIFIED: EventImportance.ValueType  # 0
EVENT_IMPORTANCE_PRODUCTION_CRITICAL: EventImportance.ValueType  # 1
EVENT_IMPORTANCE_PRODUCTION_STANDARD: EventImportance.ValueType  # 2
EVENT_IMPORTANCE_INFO: EventImportance.ValueType  # 3
EVENT_IMPORTANCE_DEBUG: EventImportance.ValueType  # 4
Global___EventImportance: _TypeAlias = EventImportance  # noqa: Y015
