"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from ...weave import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CustomLocatedAnnotationsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _CustomLocatedStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _CustomLocatedStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[CustomLocatedAnnotationsTrait._CustomLocatedStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        CUSTOM_LOCATED_STATUS_UNSPECIFIED: CustomLocatedAnnotationsTrait._CustomLocatedStatus.ValueType  # 0
        CUSTOM_LOCATED_STATUS_ANNOTATION_EXISTS: CustomLocatedAnnotationsTrait._CustomLocatedStatus.ValueType  # 1
        CUSTOM_LOCATED_STATUS_ANNOTATION_DOESNT_EXIST: CustomLocatedAnnotationsTrait._CustomLocatedStatus.ValueType  # 2
        CUSTOM_LOCATED_STATUS_MISSING_PARAMS: CustomLocatedAnnotationsTrait._CustomLocatedStatus.ValueType  # 3
        CUSTOM_LOCATED_STATUS_SUCCESS: CustomLocatedAnnotationsTrait._CustomLocatedStatus.ValueType  # 4
        CUSTOM_LOCATED_STATUS_FAILURE: CustomLocatedAnnotationsTrait._CustomLocatedStatus.ValueType  # 5

    class CustomLocatedStatus(_CustomLocatedStatus, metaclass=_CustomLocatedStatusEnumTypeWrapper): ...
    CUSTOM_LOCATED_STATUS_UNSPECIFIED: CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType  # 0
    CUSTOM_LOCATED_STATUS_ANNOTATION_EXISTS: CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType  # 1
    CUSTOM_LOCATED_STATUS_ANNOTATION_DOESNT_EXIST: CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType  # 2
    CUSTOM_LOCATED_STATUS_MISSING_PARAMS: CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType  # 3
    CUSTOM_LOCATED_STATUS_SUCCESS: CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType  # 4
    CUSTOM_LOCATED_STATUS_FAILURE: CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType  # 5

    @_typing.final
    class WheresListEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___CustomLocatedAnnotationsTrait.WhereItem: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___CustomLocatedAnnotationsTrait.WhereItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class FixturesListEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___CustomLocatedAnnotationsTrait.FixtureItem: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___CustomLocatedAnnotationsTrait.FixtureItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class WhereItem(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LABEL_FIELD_NUMBER: _builtins.int
        LEGACYUUID_FIELD_NUMBER: _builtins.int
        WHEREID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def label(self) -> _common_pb2.StringRef: ...
        @_builtins.property
        def legacyUuid(self) -> _common_pb2.StringRef: ...
        @_builtins.property
        def whereId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            label: _common_pb2.StringRef | None = ...,
            legacyUuid: _common_pb2.StringRef | None = ...,
            whereId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["label", b"label", "legacyUuid", b"legacyUuid", "whereId", b"whereId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["label", b"label", "legacyUuid", b"legacyUuid", "whereId", b"whereId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class FixtureItem(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LABEL_FIELD_NUMBER: _builtins.int
        FIXTUREID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def label(self) -> _common_pb2.StringRef: ...
        @_builtins.property
        def fixtureId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            label: _common_pb2.StringRef | None = ...,
            fixtureId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["fixtureId", b"fixtureId", "label", b"label"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["fixtureId", b"fixtureId", "label", b"label"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomWhereCreationRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LABEL_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def label(self) -> _common_pb2.StringRef: ...
        def __init__(
            self,
            *,
            label: _common_pb2.StringRef | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["label", b"label"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["label", b"label"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomWhereCreationResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        WHEREITEM_FIELD_NUMBER: _builtins.int
        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType
        @_builtins.property
        def whereItem(self) -> Global___CustomLocatedAnnotationsTrait.WhereItem: ...
        def __init__(
            self,
            *,
            whereItem: Global___CustomLocatedAnnotationsTrait.WhereItem | None = ...,
            status: Global___CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["whereItem", b"whereItem"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status", "whereItem", b"whereItem"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomWhereDeletionRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        WHEREID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def whereId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            whereId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["whereId", b"whereId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["whereId", b"whereId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomWhereDeletionResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType
        def __init__(
            self,
            *,
            status: Global___CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomFixtureCreationRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LABEL_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def label(self) -> _common_pb2.StringRef: ...
        def __init__(
            self,
            *,
            label: _common_pb2.StringRef | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["label", b"label"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["label", b"label"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomFixtureCreationResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        FIXTUREITEM_FIELD_NUMBER: _builtins.int
        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType
        @_builtins.property
        def fixtureItem(self) -> Global___CustomLocatedAnnotationsTrait.FixtureItem: ...
        def __init__(
            self,
            *,
            fixtureItem: Global___CustomLocatedAnnotationsTrait.FixtureItem | None = ...,
            status: Global___CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["fixtureItem", b"fixtureItem"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["fixtureItem", b"fixtureItem", "status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomFixtureDeletionRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        FIXTUREID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def fixtureId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            fixtureId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["fixtureId", b"fixtureId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["fixtureId", b"fixtureId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomFixtureDeletionResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType
        def __init__(
            self,
            *,
            status: Global___CustomLocatedAnnotationsTrait.CustomLocatedStatus.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomFixtureCreationEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        FIXTURE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def fixture(self) -> Global___CustomLocatedAnnotationsTrait.FixtureItem: ...
        def __init__(
            self,
            *,
            fixture: Global___CustomLocatedAnnotationsTrait.FixtureItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["fixture", b"fixture"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["fixture", b"fixture"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomWhereCreationEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        WHERE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def where(self) -> Global___CustomLocatedAnnotationsTrait.WhereItem: ...
        def __init__(
            self,
            *,
            where: Global___CustomLocatedAnnotationsTrait.WhereItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["where", b"where"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["where", b"where"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    WHERESLIST_FIELD_NUMBER: _builtins.int
    FIXTURESLIST_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def wheresList(self) -> _containers.MessageMap[_builtins.int, Global___CustomLocatedAnnotationsTrait.WhereItem]: ...
    @_builtins.property
    def fixturesList(self) -> _containers.MessageMap[_builtins.int, Global___CustomLocatedAnnotationsTrait.FixtureItem]: ...
    def __init__(
        self,
        *,
        wheresList: _abc.Mapping[_builtins.int, Global___CustomLocatedAnnotationsTrait.WhereItem] | None = ...,
        fixturesList: _abc.Mapping[_builtins.int, Global___CustomLocatedAnnotationsTrait.FixtureItem] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fixturesList", b"fixturesList", "wheresList", b"wheresList"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CustomLocatedAnnotationsTrait: _TypeAlias = CustomLocatedAnnotationsTrait  # noqa: Y015

@_typing.final
class LocatedTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _LocatedMajorFixtureType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LocatedMajorFixtureTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[LocatedTrait._LocatedMajorFixtureType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LOCATED_MAJOR_FIXTURE_TYPE_UNSPECIFIED: LocatedTrait._LocatedMajorFixtureType.ValueType  # 0
        LOCATED_MAJOR_FIXTURE_TYPE_DOOR: LocatedTrait._LocatedMajorFixtureType.ValueType  # 1
        LOCATED_MAJOR_FIXTURE_TYPE_WINDOW: LocatedTrait._LocatedMajorFixtureType.ValueType  # 2
        LOCATED_MAJOR_FIXTURE_TYPE_WALL: LocatedTrait._LocatedMajorFixtureType.ValueType  # 3
        LOCATED_MAJOR_FIXTURE_TYPE_OBJECT: LocatedTrait._LocatedMajorFixtureType.ValueType  # 4

    class LocatedMajorFixtureType(_LocatedMajorFixtureType, metaclass=_LocatedMajorFixtureTypeEnumTypeWrapper): ...
    LOCATED_MAJOR_FIXTURE_TYPE_UNSPECIFIED: LocatedTrait.LocatedMajorFixtureType.ValueType  # 0
    LOCATED_MAJOR_FIXTURE_TYPE_DOOR: LocatedTrait.LocatedMajorFixtureType.ValueType  # 1
    LOCATED_MAJOR_FIXTURE_TYPE_WINDOW: LocatedTrait.LocatedMajorFixtureType.ValueType  # 2
    LOCATED_MAJOR_FIXTURE_TYPE_WALL: LocatedTrait.LocatedMajorFixtureType.ValueType  # 3
    LOCATED_MAJOR_FIXTURE_TYPE_OBJECT: LocatedTrait.LocatedMajorFixtureType.ValueType  # 4

    class _LocatedMinorFixtureTypeDoor:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LocatedMinorFixtureTypeDoorEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[LocatedTrait._LocatedMinorFixtureTypeDoor.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LOCATED_MINOR_FIXTURE_TYPE_DOOR_UNSPECIFIED: LocatedTrait._LocatedMinorFixtureTypeDoor.ValueType  # 0
        LOCATED_MINOR_FIXTURE_TYPE_DOOR_GENERIC: LocatedTrait._LocatedMinorFixtureTypeDoor.ValueType  # 1
        LOCATED_MINOR_FIXTURE_TYPE_DOOR_HINGED: LocatedTrait._LocatedMinorFixtureTypeDoor.ValueType  # 2
        LOCATED_MINOR_FIXTURE_TYPE_DOOR_FRENCH: LocatedTrait._LocatedMinorFixtureTypeDoor.ValueType  # 3
        LOCATED_MINOR_FIXTURE_TYPE_DOOR_SLIDING: LocatedTrait._LocatedMinorFixtureTypeDoor.ValueType  # 4
        LOCATED_MINOR_FIXTURE_TYPE_DOOR_GARAGE_SEGMENTED: LocatedTrait._LocatedMinorFixtureTypeDoor.ValueType  # 5
        LOCATED_MINOR_FIXTURE_TYPE_DOOR_GARAGE_SINGLE_PANEL: LocatedTrait._LocatedMinorFixtureTypeDoor.ValueType  # 6

    class LocatedMinorFixtureTypeDoor(_LocatedMinorFixtureTypeDoor, metaclass=_LocatedMinorFixtureTypeDoorEnumTypeWrapper): ...
    LOCATED_MINOR_FIXTURE_TYPE_DOOR_UNSPECIFIED: LocatedTrait.LocatedMinorFixtureTypeDoor.ValueType  # 0
    LOCATED_MINOR_FIXTURE_TYPE_DOOR_GENERIC: LocatedTrait.LocatedMinorFixtureTypeDoor.ValueType  # 1
    LOCATED_MINOR_FIXTURE_TYPE_DOOR_HINGED: LocatedTrait.LocatedMinorFixtureTypeDoor.ValueType  # 2
    LOCATED_MINOR_FIXTURE_TYPE_DOOR_FRENCH: LocatedTrait.LocatedMinorFixtureTypeDoor.ValueType  # 3
    LOCATED_MINOR_FIXTURE_TYPE_DOOR_SLIDING: LocatedTrait.LocatedMinorFixtureTypeDoor.ValueType  # 4
    LOCATED_MINOR_FIXTURE_TYPE_DOOR_GARAGE_SEGMENTED: LocatedTrait.LocatedMinorFixtureTypeDoor.ValueType  # 5
    LOCATED_MINOR_FIXTURE_TYPE_DOOR_GARAGE_SINGLE_PANEL: LocatedTrait.LocatedMinorFixtureTypeDoor.ValueType  # 6

    class _LocatedMinorFixtureTypeWindow:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LocatedMinorFixtureTypeWindowEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[LocatedTrait._LocatedMinorFixtureTypeWindow.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LOCATED_MINOR_FIXTURE_TYPE_WINDOW_UNSPECIFIED: LocatedTrait._LocatedMinorFixtureTypeWindow.ValueType  # 0
        LOCATED_MINOR_FIXTURE_TYPE_WINDOW_GENERIC: LocatedTrait._LocatedMinorFixtureTypeWindow.ValueType  # 1
        LOCATED_MINOR_FIXTURE_TYPE_WINDOW_VERTICAL_SINGLE_HUNG: LocatedTrait._LocatedMinorFixtureTypeWindow.ValueType  # 2
        LOCATED_MINOR_FIXTURE_TYPE_WINDOW_HORIZONTAL_SINGLE_HUNG: LocatedTrait._LocatedMinorFixtureTypeWindow.ValueType  # 3
        LOCATED_MINOR_FIXTURE_TYPE_WINDOW_VERTICAL_DOUBLE_HUNG: LocatedTrait._LocatedMinorFixtureTypeWindow.ValueType  # 4
        LOCATED_MINOR_FIXTURE_TYPE_WINDOW_HORIZONTAL_DOUBLE_HUNG: LocatedTrait._LocatedMinorFixtureTypeWindow.ValueType  # 5
        LOCATED_MINOR_FIXTURE_TYPE_WINDOW_VERTICAL_CASEMENT: LocatedTrait._LocatedMinorFixtureTypeWindow.ValueType  # 6
        LOCATED_MINOR_FIXTURE_TYPE_WINDOW_HORIZONTAL_CASEMENT: LocatedTrait._LocatedMinorFixtureTypeWindow.ValueType  # 7
        LOCATED_MINOR_FIXTURE_TYPE_WINDOW_TILTTURN: LocatedTrait._LocatedMinorFixtureTypeWindow.ValueType  # 8
        LOCATED_MINOR_FIXTURE_TYPE_WINDOW_ROOF: LocatedTrait._LocatedMinorFixtureTypeWindow.ValueType  # 9

    class LocatedMinorFixtureTypeWindow(_LocatedMinorFixtureTypeWindow, metaclass=_LocatedMinorFixtureTypeWindowEnumTypeWrapper): ...
    LOCATED_MINOR_FIXTURE_TYPE_WINDOW_UNSPECIFIED: LocatedTrait.LocatedMinorFixtureTypeWindow.ValueType  # 0
    LOCATED_MINOR_FIXTURE_TYPE_WINDOW_GENERIC: LocatedTrait.LocatedMinorFixtureTypeWindow.ValueType  # 1
    LOCATED_MINOR_FIXTURE_TYPE_WINDOW_VERTICAL_SINGLE_HUNG: LocatedTrait.LocatedMinorFixtureTypeWindow.ValueType  # 2
    LOCATED_MINOR_FIXTURE_TYPE_WINDOW_HORIZONTAL_SINGLE_HUNG: LocatedTrait.LocatedMinorFixtureTypeWindow.ValueType  # 3
    LOCATED_MINOR_FIXTURE_TYPE_WINDOW_VERTICAL_DOUBLE_HUNG: LocatedTrait.LocatedMinorFixtureTypeWindow.ValueType  # 4
    LOCATED_MINOR_FIXTURE_TYPE_WINDOW_HORIZONTAL_DOUBLE_HUNG: LocatedTrait.LocatedMinorFixtureTypeWindow.ValueType  # 5
    LOCATED_MINOR_FIXTURE_TYPE_WINDOW_VERTICAL_CASEMENT: LocatedTrait.LocatedMinorFixtureTypeWindow.ValueType  # 6
    LOCATED_MINOR_FIXTURE_TYPE_WINDOW_HORIZONTAL_CASEMENT: LocatedTrait.LocatedMinorFixtureTypeWindow.ValueType  # 7
    LOCATED_MINOR_FIXTURE_TYPE_WINDOW_TILTTURN: LocatedTrait.LocatedMinorFixtureTypeWindow.ValueType  # 8
    LOCATED_MINOR_FIXTURE_TYPE_WINDOW_ROOF: LocatedTrait.LocatedMinorFixtureTypeWindow.ValueType  # 9

    class _LocatedMinorFixtureTypeWall:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LocatedMinorFixtureTypeWallEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[LocatedTrait._LocatedMinorFixtureTypeWall.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LOCATED_MINOR_FIXTURE_TYPE_WALL_UNSPECIFIED: LocatedTrait._LocatedMinorFixtureTypeWall.ValueType  # 0
        LOCATED_MINOR_FIXTURE_TYPE_WALL_GENERIC: LocatedTrait._LocatedMinorFixtureTypeWall.ValueType  # 1
        LOCATED_MINOR_FIXTURE_TYPE_WALL_CORNER: LocatedTrait._LocatedMinorFixtureTypeWall.ValueType  # 2
        LOCATED_MINOR_FIXTURE_TYPE_WALL_FLUSH: LocatedTrait._LocatedMinorFixtureTypeWall.ValueType  # 3

    class LocatedMinorFixtureTypeWall(_LocatedMinorFixtureTypeWall, metaclass=_LocatedMinorFixtureTypeWallEnumTypeWrapper): ...
    LOCATED_MINOR_FIXTURE_TYPE_WALL_UNSPECIFIED: LocatedTrait.LocatedMinorFixtureTypeWall.ValueType  # 0
    LOCATED_MINOR_FIXTURE_TYPE_WALL_GENERIC: LocatedTrait.LocatedMinorFixtureTypeWall.ValueType  # 1
    LOCATED_MINOR_FIXTURE_TYPE_WALL_CORNER: LocatedTrait.LocatedMinorFixtureTypeWall.ValueType  # 2
    LOCATED_MINOR_FIXTURE_TYPE_WALL_FLUSH: LocatedTrait.LocatedMinorFixtureTypeWall.ValueType  # 3

    class _LocatedMinorFixtureTypeObject:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LocatedMinorFixtureTypeObjectEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[LocatedTrait._LocatedMinorFixtureTypeObject.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LOCATED_MINOR_FIXTURE_TYPE_OBJECT_UNSPECIFIED: LocatedTrait._LocatedMinorFixtureTypeObject.ValueType  # 0
        LOCATED_MINOR_FIXTURE_TYPE_OBJECT_GENERIC: LocatedTrait._LocatedMinorFixtureTypeObject.ValueType  # 1

    class LocatedMinorFixtureTypeObject(_LocatedMinorFixtureTypeObject, metaclass=_LocatedMinorFixtureTypeObjectEnumTypeWrapper): ...
    LOCATED_MINOR_FIXTURE_TYPE_OBJECT_UNSPECIFIED: LocatedTrait.LocatedMinorFixtureTypeObject.ValueType  # 0
    LOCATED_MINOR_FIXTURE_TYPE_OBJECT_GENERIC: LocatedTrait.LocatedMinorFixtureTypeObject.ValueType  # 1

    @_typing.final
    class LocatedFixtureType(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        MAJORTYPE_FIELD_NUMBER: _builtins.int
        MINORTYPEDOOR_FIELD_NUMBER: _builtins.int
        MINORTYPEWINDOW_FIELD_NUMBER: _builtins.int
        MINORTYPEWALL_FIELD_NUMBER: _builtins.int
        MINORTYPEOBJECT_FIELD_NUMBER: _builtins.int
        majorType: Global___LocatedTrait.LocatedMajorFixtureType.ValueType
        minorTypeDoor: Global___LocatedTrait.LocatedMinorFixtureTypeDoor.ValueType
        minorTypeWindow: Global___LocatedTrait.LocatedMinorFixtureTypeWindow.ValueType
        minorTypeWall: Global___LocatedTrait.LocatedMinorFixtureTypeWall.ValueType
        minorTypeObject: Global___LocatedTrait.LocatedMinorFixtureTypeObject.ValueType
        def __init__(
            self,
            *,
            majorType: Global___LocatedTrait.LocatedMajorFixtureType.ValueType = ...,
            minorTypeDoor: Global___LocatedTrait.LocatedMinorFixtureTypeDoor.ValueType = ...,
            minorTypeWindow: Global___LocatedTrait.LocatedMinorFixtureTypeWindow.ValueType = ...,
            minorTypeWall: Global___LocatedTrait.LocatedMinorFixtureTypeWall.ValueType = ...,
            minorTypeObject: Global___LocatedTrait.LocatedMinorFixtureTypeObject.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["majorType", b"majorType", "minorTypeDoor", b"minorTypeDoor", "minorTypeObject", b"minorTypeObject", "minorTypeWall", b"minorTypeWall", "minorTypeWindow", b"minorTypeWindow"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LocatedTrait: _TypeAlias = LocatedTrait  # noqa: Y015

@_typing.final
class LocatedAnnotationsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _StatusCode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[LocatedAnnotationsTrait._StatusCode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATUS_CODE_UNSPECIFIED: LocatedAnnotationsTrait._StatusCode.ValueType  # 0
        STATUS_CODE_SUCCESS: LocatedAnnotationsTrait._StatusCode.ValueType  # 1
        STATUS_CODE_FAILURE: LocatedAnnotationsTrait._StatusCode.ValueType  # 2
        STATUS_CODE_MISSING_LABEL: LocatedAnnotationsTrait._StatusCode.ValueType  # 4096
        STATUS_CODE_ANNOTATION_EXISTS: LocatedAnnotationsTrait._StatusCode.ValueType  # 4097
        STATUS_CODE_MISSING_ANNOTATION: LocatedAnnotationsTrait._StatusCode.ValueType  # 8192
        STATUS_CODE_ANNOTATION_DOESNT_EXIST: LocatedAnnotationsTrait._StatusCode.ValueType  # 8193

    class StatusCode(_StatusCode, metaclass=_StatusCodeEnumTypeWrapper): ...
    STATUS_CODE_UNSPECIFIED: LocatedAnnotationsTrait.StatusCode.ValueType  # 0
    STATUS_CODE_SUCCESS: LocatedAnnotationsTrait.StatusCode.ValueType  # 1
    STATUS_CODE_FAILURE: LocatedAnnotationsTrait.StatusCode.ValueType  # 2
    STATUS_CODE_MISSING_LABEL: LocatedAnnotationsTrait.StatusCode.ValueType  # 4096
    STATUS_CODE_ANNOTATION_EXISTS: LocatedAnnotationsTrait.StatusCode.ValueType  # 4097
    STATUS_CODE_MISSING_ANNOTATION: LocatedAnnotationsTrait.StatusCode.ValueType  # 8192
    STATUS_CODE_ANNOTATION_DOESNT_EXIST: LocatedAnnotationsTrait.StatusCode.ValueType  # 8193

    @_typing.final
    class PredefinedWheresEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___LocatedAnnotationsTrait.WhereItem: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___LocatedAnnotationsTrait.WhereItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomWheresEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___LocatedAnnotationsTrait.WhereItem: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___LocatedAnnotationsTrait.WhereItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeprecatedPredefinedWheresToIncludeEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class WhereItem(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        WHEREID_FIELD_NUMBER: _builtins.int
        LABEL_FIELD_NUMBER: _builtins.int
        LEGACYUUID_FIELD_NUMBER: _builtins.int
        legacyUuid: _builtins.str
        @_builtins.property
        def whereId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def label(self) -> _common_pb2.StringRef: ...
        def __init__(
            self,
            *,
            whereId: _common_pb2.ResourceId | None = ...,
            label: _common_pb2.StringRef | None = ...,
            legacyUuid: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["label", b"label", "whereId", b"whereId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["label", b"label", "legacyUuid", b"legacyUuid", "whereId", b"whereId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomWhereCreationRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LABEL_FIELD_NUMBER: _builtins.int
        label: _builtins.str
        def __init__(
            self,
            *,
            label: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["label", b"label"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomWhereCreationResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        WHEREITEM_FIELD_NUMBER: _builtins.int
        status: Global___LocatedAnnotationsTrait.StatusCode.ValueType
        @_builtins.property
        def whereItem(self) -> Global___LocatedAnnotationsTrait.WhereItem: ...
        def __init__(
            self,
            *,
            status: Global___LocatedAnnotationsTrait.StatusCode.ValueType = ...,
            whereItem: Global___LocatedAnnotationsTrait.WhereItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["whereItem", b"whereItem"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status", "whereItem", b"whereItem"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomWhereDeletionRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        WHEREID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def whereId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            whereId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["whereId", b"whereId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["whereId", b"whereId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CustomWhereDeletionResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___LocatedAnnotationsTrait.StatusCode.ValueType
        def __init__(
            self,
            *,
            status: Global___LocatedAnnotationsTrait.StatusCode.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class GetWhereItemRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        WHEREID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def whereId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            whereId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["whereId", b"whereId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["whereId", b"whereId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class GetWhereItemResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        WHEREITEM_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def whereItem(self) -> Global___LocatedAnnotationsTrait.WhereItem: ...
        def __init__(
            self,
            *,
            whereItem: Global___LocatedAnnotationsTrait.WhereItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["whereItem", b"whereItem"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["whereItem", b"whereItem"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    PREDEFINEDWHERES_FIELD_NUMBER: _builtins.int
    CUSTOMWHERES_FIELD_NUMBER: _builtins.int
    DEPRECATEDPREDEFINEDWHERESTOINCLUDE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def predefinedWheres(self) -> _containers.MessageMap[_builtins.int, Global___LocatedAnnotationsTrait.WhereItem]: ...
    @_builtins.property
    def customWheres(self) -> _containers.MessageMap[_builtins.int, Global___LocatedAnnotationsTrait.WhereItem]: ...
    @_builtins.property
    def deprecatedPredefinedWheresToInclude(self) -> _containers.MessageMap[_builtins.int, _common_pb2.ResourceId]: ...
    def __init__(
        self,
        *,
        predefinedWheres: _abc.Mapping[_builtins.int, Global___LocatedAnnotationsTrait.WhereItem] | None = ...,
        customWheres: _abc.Mapping[_builtins.int, Global___LocatedAnnotationsTrait.WhereItem] | None = ...,
        deprecatedPredefinedWheresToInclude: _abc.Mapping[_builtins.int, _common_pb2.ResourceId] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["customWheres", b"customWheres", "deprecatedPredefinedWheresToInclude", b"deprecatedPredefinedWheresToInclude", "predefinedWheres", b"predefinedWheres"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LocatedAnnotationsTrait: _TypeAlias = LocatedAnnotationsTrait  # noqa: Y015

@_typing.final
class DeviceLocatedSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _StatusCode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DeviceLocatedSettingsTrait._StatusCode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATUS_CODE_UNSPECIFIED: DeviceLocatedSettingsTrait._StatusCode.ValueType  # 0
        STATUS_CODE_SUCCESS: DeviceLocatedSettingsTrait._StatusCode.ValueType  # 1
        STATUS_CODE_INTERNAL: DeviceLocatedSettingsTrait._StatusCode.ValueType  # 2
        STATUS_CODE_UNAUTHORIZED: DeviceLocatedSettingsTrait._StatusCode.ValueType  # 3
        STATUS_CODE_RESOURCE_NOT_FOUND: DeviceLocatedSettingsTrait._StatusCode.ValueType  # 4

    class StatusCode(_StatusCode, metaclass=_StatusCodeEnumTypeWrapper): ...
    STATUS_CODE_UNSPECIFIED: DeviceLocatedSettingsTrait.StatusCode.ValueType  # 0
    STATUS_CODE_SUCCESS: DeviceLocatedSettingsTrait.StatusCode.ValueType  # 1
    STATUS_CODE_INTERNAL: DeviceLocatedSettingsTrait.StatusCode.ValueType  # 2
    STATUS_CODE_UNAUTHORIZED: DeviceLocatedSettingsTrait.StatusCode.ValueType  # 3
    STATUS_CODE_RESOURCE_NOT_FOUND: DeviceLocatedSettingsTrait.StatusCode.ValueType  # 4

    @_typing.final
    class SetWhereRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        WHERELABEL_FIELD_NUMBER: _builtins.int
        LOCALE_FIELD_NUMBER: _builtins.int
        whereLabel: _builtins.str
        locale: _builtins.str
        def __init__(
            self,
            *,
            whereLabel: _builtins.str = ...,
            locale: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["locale", b"locale", "whereLabel", b"whereLabel"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class SetWhereResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        WHEREANNOTATIONRID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def whereAnnotationRid(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            whereAnnotationRid: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["whereAnnotationRid", b"whereAnnotationRid"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["whereAnnotationRid", b"whereAnnotationRid"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class SyncRoomAssignmentRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        RESOURCEID_FIELD_NUMBER: _builtins.int
        ROOMNAME_FIELD_NUMBER: _builtins.int
        roomName: _builtins.str
        @_builtins.property
        def resourceId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            resourceId: _common_pb2.ResourceId | None = ...,
            roomName: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId", "roomName", b"roomName"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class SyncRoomAssignmentResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        RESOURCEID_FIELD_NUMBER: _builtins.int
        status: Global___DeviceLocatedSettingsTrait.StatusCode.ValueType
        @_builtins.property
        def resourceId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            status: Global___DeviceLocatedSettingsTrait.StatusCode.ValueType = ...,
            resourceId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId", "status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    WHEREANNOTATIONRID_FIELD_NUMBER: _builtins.int
    FIXTUREANNOTATIONRID_FIELD_NUMBER: _builtins.int
    FIXTURETYPE_FIELD_NUMBER: _builtins.int
    WHERELABEL_FIELD_NUMBER: _builtins.int
    WHERESPOKENANNOTATIONRIDS_FIELD_NUMBER: _builtins.int
    FIXTURENAMELABEL_FIELD_NUMBER: _builtins.int
    FIXTURESPOKENANNOTATIONRIDS_FIELD_NUMBER: _builtins.int
    LASTMODIFIEDTIMESTAMP_FIELD_NUMBER: _builtins.int
    LASTKNOWNRELOCATIONTIMESTAMP_FIELD_NUMBER: _builtins.int
    WHERELEGACYUUID_FIELD_NUMBER: _builtins.int
    whereLegacyUuid: _builtins.str
    @_builtins.property
    def whereAnnotationRid(self) -> _common_pb2.ResourceId: ...
    @_builtins.property
    def fixtureAnnotationRid(self) -> _common_pb2.ResourceId: ...
    @_builtins.property
    def fixtureType(self) -> Global___LocatedTrait.LocatedFixtureType: ...
    @_builtins.property
    def whereLabel(self) -> _common_pb2.StringRef: ...
    @_builtins.property
    def whereSpokenAnnotationRids(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.ResourceId]: ...
    @_builtins.property
    def fixtureNameLabel(self) -> _common_pb2.StringRef: ...
    @_builtins.property
    def fixtureSpokenAnnotationRids(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.ResourceId]: ...
    @_builtins.property
    def lastModifiedTimestamp(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lastKnownRelocationTimestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        whereAnnotationRid: _common_pb2.ResourceId | None = ...,
        fixtureAnnotationRid: _common_pb2.ResourceId | None = ...,
        fixtureType: Global___LocatedTrait.LocatedFixtureType | None = ...,
        whereLabel: _common_pb2.StringRef | None = ...,
        whereSpokenAnnotationRids: _abc.Iterable[_common_pb2.ResourceId] | None = ...,
        fixtureNameLabel: _common_pb2.StringRef | None = ...,
        fixtureSpokenAnnotationRids: _abc.Iterable[_common_pb2.ResourceId] | None = ...,
        lastModifiedTimestamp: _timestamp_pb2.Timestamp | None = ...,
        lastKnownRelocationTimestamp: _timestamp_pb2.Timestamp | None = ...,
        whereLegacyUuid: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fixtureAnnotationRid", b"fixtureAnnotationRid", "fixtureNameLabel", b"fixtureNameLabel", "fixtureType", b"fixtureType", "lastKnownRelocationTimestamp", b"lastKnownRelocationTimestamp", "lastModifiedTimestamp", b"lastModifiedTimestamp", "whereAnnotationRid", b"whereAnnotationRid", "whereLabel", b"whereLabel"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fixtureAnnotationRid", b"fixtureAnnotationRid", "fixtureNameLabel", b"fixtureNameLabel", "fixtureSpokenAnnotationRids", b"fixtureSpokenAnnotationRids", "fixtureType", b"fixtureType", "lastKnownRelocationTimestamp", b"lastKnownRelocationTimestamp", "lastModifiedTimestamp", b"lastModifiedTimestamp", "whereAnnotationRid", b"whereAnnotationRid", "whereLabel", b"whereLabel", "whereLegacyUuid", b"whereLegacyUuid", "whereSpokenAnnotationRids", b"whereSpokenAnnotationRids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceLocatedSettingsTrait: _TypeAlias = DeviceLocatedSettingsTrait  # noqa: Y015

@_typing.final
class GeoCommon(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class GeoCoordinateStruct(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LATITUDE_FIELD_NUMBER: _builtins.int
        LONGITUDE_FIELD_NUMBER: _builtins.int
        latitude: _builtins.float
        longitude: _builtins.float
        def __init__(
            self,
            *,
            latitude: _builtins.float = ...,
            longitude: _builtins.float = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["latitude", b"latitude", "longitude", b"longitude"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class PostalAddress(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        POSTALCODE_FIELD_NUMBER: _builtins.int
        REGIONCODE_FIELD_NUMBER: _builtins.int
        ADDRESSLINES_FIELD_NUMBER: _builtins.int
        LOCALITY_FIELD_NUMBER: _builtins.int
        ADMINISTRATIVEAREA_FIELD_NUMBER: _builtins.int
        regionCode: _builtins.str
        @_builtins.property
        def postalCode(self) -> _wrappers_pb2.StringValue: ...
        @_builtins.property
        def addressLines(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        @_builtins.property
        def locality(self) -> _wrappers_pb2.StringValue: ...
        @_builtins.property
        def administrativeArea(self) -> _wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            postalCode: _wrappers_pb2.StringValue | None = ...,
            regionCode: _builtins.str = ...,
            addressLines: _abc.Iterable[_builtins.str] | None = ...,
            locality: _wrappers_pb2.StringValue | None = ...,
            administrativeArea: _wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["administrativeArea", b"administrativeArea", "locality", b"locality", "postalCode", b"postalCode"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["addressLines", b"addressLines", "administrativeArea", b"administrativeArea", "locality", b"locality", "postalCode", b"postalCode", "regionCode", b"regionCode"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GeoCommon: _TypeAlias = GeoCommon  # noqa: Y015

@_typing.final
class DeviceLocatedCapabilitiesTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALIDWHEREANNOTATIONRIDS_FIELD_NUMBER: _builtins.int
    VALIDWHERESPOKENANNOTATIONRIDS_FIELD_NUMBER: _builtins.int
    VALIDFIXTUREANNOTATIONRIDS_FIELD_NUMBER: _builtins.int
    VALIDFIXTURESPOKENANNOTATIONRIDS_FIELD_NUMBER: _builtins.int
    VALIDFIXTURETYPES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def validWhereAnnotationRids(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.ResourceId]: ...
    @_builtins.property
    def validWhereSpokenAnnotationRids(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.ResourceId]: ...
    @_builtins.property
    def validFixtureAnnotationRids(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.ResourceId]: ...
    @_builtins.property
    def validFixtureSpokenAnnotationRids(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.ResourceId]: ...
    @_builtins.property
    def validFixtureTypes(self) -> _containers.RepeatedCompositeFieldContainer[Global___LocatedTrait.LocatedFixtureType]: ...
    def __init__(
        self,
        *,
        validWhereAnnotationRids: _abc.Iterable[_common_pb2.ResourceId] | None = ...,
        validWhereSpokenAnnotationRids: _abc.Iterable[_common_pb2.ResourceId] | None = ...,
        validFixtureAnnotationRids: _abc.Iterable[_common_pb2.ResourceId] | None = ...,
        validFixtureSpokenAnnotationRids: _abc.Iterable[_common_pb2.ResourceId] | None = ...,
        validFixtureTypes: _abc.Iterable[Global___LocatedTrait.LocatedFixtureType] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["validFixtureAnnotationRids", b"validFixtureAnnotationRids", "validFixtureSpokenAnnotationRids", b"validFixtureSpokenAnnotationRids", "validFixtureTypes", b"validFixtureTypes", "validWhereAnnotationRids", b"validWhereAnnotationRids", "validWhereSpokenAnnotationRids", b"validWhereSpokenAnnotationRids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceLocatedCapabilitiesTrait: _TypeAlias = DeviceLocatedCapabilitiesTrait  # noqa: Y015
