"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.rpc import status_pb2 as _status_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class StreamBody(_message.Message):
    """The envelope the gRPC-web gateway wraps a server-streaming response in.

    Only the two fields this integration reads are declared. Upstream may carry
    more (the canonical definition is not published alongside status.proto), but
    protobuf keeps unrecognised fields as unknown fields, so a partial
    declaration parses the wire format correctly.

    `message` is `bytes` rather than a concrete type because StreamBody is
    generic over the RPC being streamed. For the Observe RPC each entry is a
    serialized nestlabs.gateway.v2.ObserveResponse.ObserveResponse.
    """

    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def message(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    @_builtins.property
    def status(self) -> _status_pb2.Status: ...
    def __init__(
        self,
        *,
        message: _abc.Iterable[_builtins.bytes] | None = ...,
        status: _status_pb2.Status | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamBody: _TypeAlias = StreamBody  # noqa: Y015
