blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community forum
    url: https://community.home-assistant.io/t/support-for-nest-protect/310084
    about: Please ask and answer questions here.
