name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: >-
        Describe your feature request here to communicate to the
        maintainers. Tell us what you were trying to do and why.

        Provide a clear and concise description of what the feature request is. What would you like to happen?

  - type: markdown
    attributes:
      value: |
        ## Device

  - type: input
    id: nest_device_model
    validations:
      required: false
    attributes:
      label: Device (optional)
      placeholder: e.g. Nest Protect (Wired)
      description: >
        Can be found in the Configuration panel -> Integrations -> Nest Protect -> (x) devices -> Model.

  - type: markdown
    attributes:
      value: |
        ## Details

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: If you have any additional information for us, use the field below. Please note, you can attach screenshots or screen recordings here, by dragging and dropping files in the field below.

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
