"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SchemaVersion(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CURRENTVERSION_FIELD_NUMBER: _builtins.int
    MINCOMPATVERSION_FIELD_NUMBER: _builtins.int
    currentVersion: _builtins.int
    minCompatVersion: _builtins.int
    def __init__(
        self,
        *,
        currentVersion: _builtins.int = ...,
        minCompatVersion: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["currentVersion", b"currentVersion", "minCompatVersion", b"minCompatVersion"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SchemaVersion: _TypeAlias = SchemaVersion  # noqa: Y015
