"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from ...weave import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SoftwareComponentTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SoftwareComponentTypeStruct(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        COMPONENTNAME_FIELD_NUMBER: _builtins.int
        COMPONENTVERSION_FIELD_NUMBER: _builtins.int
        componentName: _builtins.str
        componentVersion: _builtins.str
        def __init__(
            self,
            *,
            componentName: _builtins.str = ...,
            componentVersion: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["componentName", b"componentName", "componentVersion", b"componentVersion"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SOFTWARECOMPONENTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def softwareComponents(self) -> _containers.RepeatedCompositeFieldContainer[Global___SoftwareComponentTrait.SoftwareComponentTypeStruct]: ...
    def __init__(
        self,
        *,
        softwareComponents: _abc.Iterable[Global___SoftwareComponentTrait.SoftwareComponentTypeStruct] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["softwareComponents", b"softwareComponents"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SoftwareComponentTrait: _TypeAlias = SoftwareComponentTrait  # noqa: Y015

@_typing.final
class DeviceIdentityTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VENDORID_FIELD_NUMBER: _builtins.int
    VENDORIDDESCRIPTION_FIELD_NUMBER: _builtins.int
    VENDORPRODUCTID_FIELD_NUMBER: _builtins.int
    PRODUCTIDDESCRIPTION_FIELD_NUMBER: _builtins.int
    PRODUCTREVISION_FIELD_NUMBER: _builtins.int
    SERIALNUMBER_FIELD_NUMBER: _builtins.int
    SOFTWAREVERSION_FIELD_NUMBER: _builtins.int
    MANUFACTURINGDATE_FIELD_NUMBER: _builtins.int
    DEVICEID_FIELD_NUMBER: _builtins.int
    FABRICID_FIELD_NUMBER: _builtins.int
    vendorId: _builtins.int
    vendorProductId: _builtins.int
    productRevision: _builtins.int
    serialNumber: _builtins.str
    softwareVersion: _builtins.str
    fabricId: _builtins.int
    @_builtins.property
    def vendorIdDescription(self) -> _common_pb2.StringRef: ...
    @_builtins.property
    def productIdDescription(self) -> _common_pb2.StringRef: ...
    @_builtins.property
    def manufacturingDate(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def deviceId(self) -> _common_pb2.ResourceId: ...
    def __init__(
        self,
        *,
        vendorId: _builtins.int = ...,
        vendorIdDescription: _common_pb2.StringRef | None = ...,
        vendorProductId: _builtins.int = ...,
        productIdDescription: _common_pb2.StringRef | None = ...,
        productRevision: _builtins.int = ...,
        serialNumber: _builtins.str = ...,
        softwareVersion: _builtins.str = ...,
        manufacturingDate: _wrappers_pb2.StringValue | None = ...,
        deviceId: _common_pb2.ResourceId | None = ...,
        fabricId: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["deviceId", b"deviceId", "manufacturingDate", b"manufacturingDate", "productIdDescription", b"productIdDescription", "vendorIdDescription", b"vendorIdDescription"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deviceId", b"deviceId", "fabricId", b"fabricId", "manufacturingDate", b"manufacturingDate", "productIdDescription", b"productIdDescription", "productRevision", b"productRevision", "serialNumber", b"serialNumber", "softwareVersion", b"softwareVersion", "vendorId", b"vendorId", "vendorIdDescription", b"vendorIdDescription", "vendorProductId", b"vendorProductId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeviceIdentityTrait: _TypeAlias = DeviceIdentityTrait  # noqa: Y015

@_typing.final
class LabelSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LABEL_FIELD_NUMBER: _builtins.int
    label: _builtins.str
    def __init__(
        self,
        *,
        label: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["label", b"label"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LabelSettingsTrait: _TypeAlias = LabelSettingsTrait  # noqa: Y015
