"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class LivenessTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _LivenessDeviceStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LivenessDeviceStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[LivenessTrait._LivenessDeviceStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LIVENESS_DEVICE_STATUS_UNSPECIFIED: LivenessTrait._LivenessDeviceStatus.ValueType  # 0
        LIVENESS_DEVICE_STATUS_ONLINE: LivenessTrait._LivenessDeviceStatus.ValueType  # 1
        LIVENESS_DEVICE_STATUS_UNREACHABLE: LivenessTrait._LivenessDeviceStatus.ValueType  # 2
        LIVENESS_DEVICE_STATUS_UNINITIALIZED: LivenessTrait._LivenessDeviceStatus.ValueType  # 3
        LIVENESS_DEVICE_STATUS_REBOOTING: LivenessTrait._LivenessDeviceStatus.ValueType  # 4
        LIVENESS_DEVICE_STATUS_UPGRADING: LivenessTrait._LivenessDeviceStatus.ValueType  # 5
        LIVENESS_DEVICE_STATUS_SCHEDULED_DOWN: LivenessTrait._LivenessDeviceStatus.ValueType  # 6

    class LivenessDeviceStatus(_LivenessDeviceStatus, metaclass=_LivenessDeviceStatusEnumTypeWrapper): ...
    LIVENESS_DEVICE_STATUS_UNSPECIFIED: LivenessTrait.LivenessDeviceStatus.ValueType  # 0
    LIVENESS_DEVICE_STATUS_ONLINE: LivenessTrait.LivenessDeviceStatus.ValueType  # 1
    LIVENESS_DEVICE_STATUS_UNREACHABLE: LivenessTrait.LivenessDeviceStatus.ValueType  # 2
    LIVENESS_DEVICE_STATUS_UNINITIALIZED: LivenessTrait.LivenessDeviceStatus.ValueType  # 3
    LIVENESS_DEVICE_STATUS_REBOOTING: LivenessTrait.LivenessDeviceStatus.ValueType  # 4
    LIVENESS_DEVICE_STATUS_UPGRADING: LivenessTrait.LivenessDeviceStatus.ValueType  # 5
    LIVENESS_DEVICE_STATUS_SCHEDULED_DOWN: LivenessTrait.LivenessDeviceStatus.ValueType  # 6

    class _DeviceFrontendType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _DeviceFrontendTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[LivenessTrait._DeviceFrontendType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DEVICE_FRONTEND_TYPE_UNSPECIFIED: LivenessTrait._DeviceFrontendType.ValueType  # 0
        DEVICE_FRONTEND_TYPE_LYCRA: LivenessTrait._DeviceFrontendType.ValueType  # 1
        DEVICE_FRONTEND_TYPE_WEAVE_FE_1: LivenessTrait._DeviceFrontendType.ValueType  # 2

    class DeviceFrontendType(_DeviceFrontendType, metaclass=_DeviceFrontendTypeEnumTypeWrapper): ...
    DEVICE_FRONTEND_TYPE_UNSPECIFIED: LivenessTrait.DeviceFrontendType.ValueType  # 0
    DEVICE_FRONTEND_TYPE_LYCRA: LivenessTrait.DeviceFrontendType.ValueType  # 1
    DEVICE_FRONTEND_TYPE_WEAVE_FE_1: LivenessTrait.DeviceFrontendType.ValueType  # 2

    @_typing.final
    class LivenessChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        HEARTBEATSTATUS_FIELD_NUMBER: _builtins.int
        NOTIFYREQUESTUNRESPONSIVENESS_FIELD_NUMBER: _builtins.int
        COMMANDREQUESTUNRESPONSIVENESS_FIELD_NUMBER: _builtins.int
        PREVSTATUS_FIELD_NUMBER: _builtins.int
        TUNNELDISCONNECTED_FIELD_NUMBER: _builtins.int
        LASTCONTACTEDTIME_FIELD_NUMBER: _builtins.int
        LASTWDMHEARTBEATTIME_FIELD_NUMBER: _builtins.int
        TUNNELCLOSEDTIME_FIELD_NUMBER: _builtins.int
        TIMESTATUSCHANGED_FIELD_NUMBER: _builtins.int
        TIMEPREVSTATUSCHANGED_FIELD_NUMBER: _builtins.int
        FRONTEND_FIELD_NUMBER: _builtins.int
        DISCONNECTED_FIELD_NUMBER: _builtins.int
        DISCONNECTEDTIMESTATUSCHANGED_FIELD_NUMBER: _builtins.int
        CONNECTIONCLOSEDTIME_FIELD_NUMBER: _builtins.int
        TRAITLABEL_FIELD_NUMBER: _builtins.int
        status: Global___LivenessTrait.LivenessDeviceStatus.ValueType
        heartbeatStatus: Global___LivenessTrait.LivenessDeviceStatus.ValueType
        prevStatus: Global___LivenessTrait.LivenessDeviceStatus.ValueType
        @_builtins.property
        def notifyRequestUnresponsiveness(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def commandRequestUnresponsiveness(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def tunnelDisconnected(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def lastContactedTime(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def lastWdmHeartbeatTime(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def tunnelClosedTime(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def timeStatusChanged(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def timePrevStatusChanged(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def frontend(self) -> _containers.RepeatedScalarFieldContainer[Global___LivenessTrait.DeviceFrontendType.ValueType]: ...
        @_builtins.property
        def disconnected(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def disconnectedTimeStatusChanged(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def connectionClosedTime(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def traitLabel(self) -> _wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            status: Global___LivenessTrait.LivenessDeviceStatus.ValueType = ...,
            heartbeatStatus: Global___LivenessTrait.LivenessDeviceStatus.ValueType = ...,
            notifyRequestUnresponsiveness: _wrappers_pb2.BoolValue | None = ...,
            commandRequestUnresponsiveness: _wrappers_pb2.BoolValue | None = ...,
            prevStatus: Global___LivenessTrait.LivenessDeviceStatus.ValueType = ...,
            tunnelDisconnected: _wrappers_pb2.BoolValue | None = ...,
            lastContactedTime: _timestamp_pb2.Timestamp | None = ...,
            lastWdmHeartbeatTime: _timestamp_pb2.Timestamp | None = ...,
            tunnelClosedTime: _timestamp_pb2.Timestamp | None = ...,
            timeStatusChanged: _timestamp_pb2.Timestamp | None = ...,
            timePrevStatusChanged: _timestamp_pb2.Timestamp | None = ...,
            frontend: _abc.Iterable[Global___LivenessTrait.DeviceFrontendType.ValueType] | None = ...,
            disconnected: _wrappers_pb2.BoolValue | None = ...,
            disconnectedTimeStatusChanged: _timestamp_pb2.Timestamp | None = ...,
            connectionClosedTime: _timestamp_pb2.Timestamp | None = ...,
            traitLabel: _wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["commandRequestUnresponsiveness", b"commandRequestUnresponsiveness", "connectionClosedTime", b"connectionClosedTime", "disconnected", b"disconnected", "disconnectedTimeStatusChanged", b"disconnectedTimeStatusChanged", "lastContactedTime", b"lastContactedTime", "lastWdmHeartbeatTime", b"lastWdmHeartbeatTime", "notifyRequestUnresponsiveness", b"notifyRequestUnresponsiveness", "timePrevStatusChanged", b"timePrevStatusChanged", "timeStatusChanged", b"timeStatusChanged", "traitLabel", b"traitLabel", "tunnelClosedTime", b"tunnelClosedTime", "tunnelDisconnected", b"tunnelDisconnected"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["commandRequestUnresponsiveness", b"commandRequestUnresponsiveness", "connectionClosedTime", b"connectionClosedTime", "disconnected", b"disconnected", "disconnectedTimeStatusChanged", b"disconnectedTimeStatusChanged", "frontend", b"frontend", "heartbeatStatus", b"heartbeatStatus", "lastContactedTime", b"lastContactedTime", "lastWdmHeartbeatTime", b"lastWdmHeartbeatTime", "notifyRequestUnresponsiveness", b"notifyRequestUnresponsiveness", "prevStatus", b"prevStatus", "status", b"status", "timePrevStatusChanged", b"timePrevStatusChanged", "timeStatusChanged", b"timeStatusChanged", "traitLabel", b"traitLabel", "tunnelClosedTime", b"tunnelClosedTime", "tunnelDisconnected", b"tunnelDisconnected"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LivenessConnectedSignalEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CONNECTIONID_FIELD_NUMBER: _builtins.int
        FRONTEND_FIELD_NUMBER: _builtins.int
        OCCURRENCETIME_FIELD_NUMBER: _builtins.int
        CONNECTIONTAG_FIELD_NUMBER: _builtins.int
        connectionId: _builtins.str
        frontend: Global___LivenessTrait.DeviceFrontendType.ValueType
        @_builtins.property
        def occurrenceTime(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def connectionTag(self) -> _wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            connectionId: _builtins.str = ...,
            frontend: Global___LivenessTrait.DeviceFrontendType.ValueType = ...,
            occurrenceTime: _timestamp_pb2.Timestamp | None = ...,
            connectionTag: _wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["connectionTag", b"connectionTag", "occurrenceTime", b"occurrenceTime"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["connectionId", b"connectionId", "connectionTag", b"connectionTag", "frontend", b"frontend", "occurrenceTime", b"occurrenceTime"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LivenessDisconnectedSignalEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CONNECTIONID_FIELD_NUMBER: _builtins.int
        FRONTEND_FIELD_NUMBER: _builtins.int
        OCCURRENCETIME_FIELD_NUMBER: _builtins.int
        CONNECTIONTAG_FIELD_NUMBER: _builtins.int
        connectionId: _builtins.str
        frontend: Global___LivenessTrait.DeviceFrontendType.ValueType
        @_builtins.property
        def occurrenceTime(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def connectionTag(self) -> _wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            connectionId: _builtins.str = ...,
            frontend: Global___LivenessTrait.DeviceFrontendType.ValueType = ...,
            occurrenceTime: _timestamp_pb2.Timestamp | None = ...,
            connectionTag: _wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["connectionTag", b"connectionTag", "occurrenceTime", b"occurrenceTime"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["connectionId", b"connectionId", "connectionTag", b"connectionTag", "frontend", b"frontend", "occurrenceTime", b"occurrenceTime"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    STATUS_FIELD_NUMBER: _builtins.int
    TIMESTATUSCHANGED_FIELD_NUMBER: _builtins.int
    MAXINACTIVITYDURATION_FIELD_NUMBER: _builtins.int
    HEARTBEATSTATUS_FIELD_NUMBER: _builtins.int
    TIMEHEARTBEATSTATUSCHANGED_FIELD_NUMBER: _builtins.int
    NOTIFYREQUESTUNRESPONSIVENESS_FIELD_NUMBER: _builtins.int
    NOTIFYREQUESTUNRESPONSIVENESSTIMESTATUSCHANGED_FIELD_NUMBER: _builtins.int
    COMMANDREQUESTUNRESPONSIVENESS_FIELD_NUMBER: _builtins.int
    COMMANDREQUESTUNRESPONSIVENESSTIMESTATUSCHANGED_FIELD_NUMBER: _builtins.int
    PUBLISHERNAME_FIELD_NUMBER: _builtins.int
    TUNNELDISCONNECTED_FIELD_NUMBER: _builtins.int
    TUNNELDISCONNECTEDTIMESTATUSCHANGED_FIELD_NUMBER: _builtins.int
    LASTCONTACTEDTIME_FIELD_NUMBER: _builtins.int
    LASTWDMHEARTBEATTIME_FIELD_NUMBER: _builtins.int
    TUNNELCLOSEDTIME_FIELD_NUMBER: _builtins.int
    FRONTEND_FIELD_NUMBER: _builtins.int
    DISCONNECTED_FIELD_NUMBER: _builtins.int
    DISCONNECTEDTIMESTATUSCHANGED_FIELD_NUMBER: _builtins.int
    CONNECTIONCLOSEDTIME_FIELD_NUMBER: _builtins.int
    status: Global___LivenessTrait.LivenessDeviceStatus.ValueType
    heartbeatStatus: Global___LivenessTrait.LivenessDeviceStatus.ValueType
    @_builtins.property
    def timeStatusChanged(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def maxInactivityDuration(self) -> _duration_pb2.Duration: ...
    @_builtins.property
    def timeHeartbeatStatusChanged(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def notifyRequestUnresponsiveness(self) -> _wrappers_pb2.BoolValue: ...
    @_builtins.property
    def notifyRequestUnresponsivenessTimeStatusChanged(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def commandRequestUnresponsiveness(self) -> _wrappers_pb2.BoolValue: ...
    @_builtins.property
    def commandRequestUnresponsivenessTimeStatusChanged(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def publisherName(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def tunnelDisconnected(self) -> _wrappers_pb2.BoolValue: ...
    @_builtins.property
    def tunnelDisconnectedTimeStatusChanged(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lastContactedTime(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lastWdmHeartbeatTime(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def tunnelClosedTime(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def frontend(self) -> _containers.RepeatedScalarFieldContainer[Global___LivenessTrait.DeviceFrontendType.ValueType]: ...
    @_builtins.property
    def disconnected(self) -> _wrappers_pb2.BoolValue: ...
    @_builtins.property
    def disconnectedTimeStatusChanged(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def connectionClosedTime(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        status: Global___LivenessTrait.LivenessDeviceStatus.ValueType = ...,
        timeStatusChanged: _timestamp_pb2.Timestamp | None = ...,
        maxInactivityDuration: _duration_pb2.Duration | None = ...,
        heartbeatStatus: Global___LivenessTrait.LivenessDeviceStatus.ValueType = ...,
        timeHeartbeatStatusChanged: _timestamp_pb2.Timestamp | None = ...,
        notifyRequestUnresponsiveness: _wrappers_pb2.BoolValue | None = ...,
        notifyRequestUnresponsivenessTimeStatusChanged: _timestamp_pb2.Timestamp | None = ...,
        commandRequestUnresponsiveness: _wrappers_pb2.BoolValue | None = ...,
        commandRequestUnresponsivenessTimeStatusChanged: _timestamp_pb2.Timestamp | None = ...,
        publisherName: _wrappers_pb2.StringValue | None = ...,
        tunnelDisconnected: _wrappers_pb2.BoolValue | None = ...,
        tunnelDisconnectedTimeStatusChanged: _timestamp_pb2.Timestamp | None = ...,
        lastContactedTime: _timestamp_pb2.Timestamp | None = ...,
        lastWdmHeartbeatTime: _timestamp_pb2.Timestamp | None = ...,
        tunnelClosedTime: _timestamp_pb2.Timestamp | None = ...,
        frontend: _abc.Iterable[Global___LivenessTrait.DeviceFrontendType.ValueType] | None = ...,
        disconnected: _wrappers_pb2.BoolValue | None = ...,
        disconnectedTimeStatusChanged: _timestamp_pb2.Timestamp | None = ...,
        connectionClosedTime: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["commandRequestUnresponsiveness", b"commandRequestUnresponsiveness", "commandRequestUnresponsivenessTimeStatusChanged", b"commandRequestUnresponsivenessTimeStatusChanged", "connectionClosedTime", b"connectionClosedTime", "disconnected", b"disconnected", "disconnectedTimeStatusChanged", b"disconnectedTimeStatusChanged", "lastContactedTime", b"lastContactedTime", "lastWdmHeartbeatTime", b"lastWdmHeartbeatTime", "maxInactivityDuration", b"maxInactivityDuration", "notifyRequestUnresponsiveness", b"notifyRequestUnresponsiveness", "notifyRequestUnresponsivenessTimeStatusChanged", b"notifyRequestUnresponsivenessTimeStatusChanged", "publisherName", b"publisherName", "timeHeartbeatStatusChanged", b"timeHeartbeatStatusChanged", "timeStatusChanged", b"timeStatusChanged", "tunnelClosedTime", b"tunnelClosedTime", "tunnelDisconnected", b"tunnelDisconnected", "tunnelDisconnectedTimeStatusChanged", b"tunnelDisconnectedTimeStatusChanged"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commandRequestUnresponsiveness", b"commandRequestUnresponsiveness", "commandRequestUnresponsivenessTimeStatusChanged", b"commandRequestUnresponsivenessTimeStatusChanged", "connectionClosedTime", b"connectionClosedTime", "disconnected", b"disconnected", "disconnectedTimeStatusChanged", b"disconnectedTimeStatusChanged", "frontend", b"frontend", "heartbeatStatus", b"heartbeatStatus", "lastContactedTime", b"lastContactedTime", "lastWdmHeartbeatTime", b"lastWdmHeartbeatTime", "maxInactivityDuration", b"maxInactivityDuration", "notifyRequestUnresponsiveness", b"notifyRequestUnresponsiveness", "notifyRequestUnresponsivenessTimeStatusChanged", b"notifyRequestUnresponsivenessTimeStatusChanged", "publisherName", b"publisherName", "status", b"status", "timeHeartbeatStatusChanged", b"timeHeartbeatStatusChanged", "timeStatusChanged", b"timeStatusChanged", "tunnelClosedTime", b"tunnelClosedTime", "tunnelDisconnected", b"tunnelDisconnected", "tunnelDisconnectedTimeStatusChanged", b"tunnelDisconnectedTimeStatusChanged"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LivenessTrait: _TypeAlias = LivenessTrait  # noqa: Y015
