"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from ...weave import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PowerSourceTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _PowerSourceCondition:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PowerSourceConditionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[PowerSourceTrait._PowerSourceCondition.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        POWER_SOURCE_CONDITION_UNSPECIFIED: PowerSourceTrait._PowerSourceCondition.ValueType  # 0
        POWER_SOURCE_CONDITION_NOMINAL: PowerSourceTrait._PowerSourceCondition.ValueType  # 1
        POWER_SOURCE_CONDITION_CRITICAL: PowerSourceTrait._PowerSourceCondition.ValueType  # 2

    class PowerSourceCondition(_PowerSourceCondition, metaclass=_PowerSourceConditionEnumTypeWrapper): ...
    POWER_SOURCE_CONDITION_UNSPECIFIED: PowerSourceTrait.PowerSourceCondition.ValueType  # 0
    POWER_SOURCE_CONDITION_NOMINAL: PowerSourceTrait.PowerSourceCondition.ValueType  # 1
    POWER_SOURCE_CONDITION_CRITICAL: PowerSourceTrait.PowerSourceCondition.ValueType  # 2

    class _PowerSourceStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PowerSourceStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[PowerSourceTrait._PowerSourceStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        POWER_SOURCE_STATUS_UNSPECIFIED: PowerSourceTrait._PowerSourceStatus.ValueType  # 0
        POWER_SOURCE_STATUS_ACTIVE: PowerSourceTrait._PowerSourceStatus.ValueType  # 1
        POWER_SOURCE_STATUS_STANDBY: PowerSourceTrait._PowerSourceStatus.ValueType  # 2
        POWER_SOURCE_STATUS_INACTIVE: PowerSourceTrait._PowerSourceStatus.ValueType  # 3

    class PowerSourceStatus(_PowerSourceStatus, metaclass=_PowerSourceStatusEnumTypeWrapper): ...
    POWER_SOURCE_STATUS_UNSPECIFIED: PowerSourceTrait.PowerSourceStatus.ValueType  # 0
    POWER_SOURCE_STATUS_ACTIVE: PowerSourceTrait.PowerSourceStatus.ValueType  # 1
    POWER_SOURCE_STATUS_STANDBY: PowerSourceTrait.PowerSourceStatus.ValueType  # 2
    POWER_SOURCE_STATUS_INACTIVE: PowerSourceTrait.PowerSourceStatus.ValueType  # 3

    @_typing.final
    class PowerSourceChangedEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CONDITION_FIELD_NUMBER: _builtins.int
        STATUS_FIELD_NUMBER: _builtins.int
        condition: Global___PowerSourceTrait.PowerSourceCondition.ValueType
        status: Global___PowerSourceTrait.PowerSourceStatus.ValueType
        def __init__(
            self,
            *,
            condition: Global___PowerSourceTrait.PowerSourceCondition.ValueType = ...,
            status: Global___PowerSourceTrait.PowerSourceStatus.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["condition", b"condition", "status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TYPE_FIELD_NUMBER: _builtins.int
    ASSESSEDVOLTAGE_FIELD_NUMBER: _builtins.int
    ASSESSEDCURRENT_FIELD_NUMBER: _builtins.int
    ASSESSEDFREQUENCY_FIELD_NUMBER: _builtins.int
    CONDITION_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    PRESENT_FIELD_NUMBER: _builtins.int
    type: Global___PowerSourceCapabilitiesTrait.PowerSourceType.ValueType
    condition: Global___PowerSourceTrait.PowerSourceCondition.ValueType
    status: Global___PowerSourceTrait.PowerSourceStatus.ValueType
    present: _builtins.bool
    @_builtins.property
    def assessedVoltage(self) -> _wrappers_pb2.FloatValue: ...
    @_builtins.property
    def assessedCurrent(self) -> _wrappers_pb2.FloatValue: ...
    @_builtins.property
    def assessedFrequency(self) -> _wrappers_pb2.FloatValue: ...
    def __init__(
        self,
        *,
        type: Global___PowerSourceCapabilitiesTrait.PowerSourceType.ValueType = ...,
        assessedVoltage: _wrappers_pb2.FloatValue | None = ...,
        assessedCurrent: _wrappers_pb2.FloatValue | None = ...,
        assessedFrequency: _wrappers_pb2.FloatValue | None = ...,
        condition: Global___PowerSourceTrait.PowerSourceCondition.ValueType = ...,
        status: Global___PowerSourceTrait.PowerSourceStatus.ValueType = ...,
        present: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["assessedCurrent", b"assessedCurrent", "assessedFrequency", b"assessedFrequency", "assessedVoltage", b"assessedVoltage"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["assessedCurrent", b"assessedCurrent", "assessedFrequency", b"assessedFrequency", "assessedVoltage", b"assessedVoltage", "condition", b"condition", "present", b"present", "status", b"status", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PowerSourceTrait: _TypeAlias = PowerSourceTrait  # noqa: Y015

@_typing.final
class PowerSourceCapabilitiesTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _PowerSourceType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PowerSourceTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[PowerSourceCapabilitiesTrait._PowerSourceType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        POWER_SOURCE_TYPE_UNSPECIFIED: PowerSourceCapabilitiesTrait._PowerSourceType.ValueType  # 0
        POWER_SOURCE_TYPE_BATTERY: PowerSourceCapabilitiesTrait._PowerSourceType.ValueType  # 1
        POWER_SOURCE_TYPE_RECHARGEABLE_BATTERY: PowerSourceCapabilitiesTrait._PowerSourceType.ValueType  # 2

    class PowerSourceType(_PowerSourceType, metaclass=_PowerSourceTypeEnumTypeWrapper): ...
    POWER_SOURCE_TYPE_UNSPECIFIED: PowerSourceCapabilitiesTrait.PowerSourceType.ValueType  # 0
    POWER_SOURCE_TYPE_BATTERY: PowerSourceCapabilitiesTrait.PowerSourceType.ValueType  # 1
    POWER_SOURCE_TYPE_RECHARGEABLE_BATTERY: PowerSourceCapabilitiesTrait.PowerSourceType.ValueType  # 2

    class _PowerSourceCurrentType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PowerSourceCurrentTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[PowerSourceCapabilitiesTrait._PowerSourceCurrentType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        POWER_SOURCE_CURRENT_TYPE_UNSPECIFIED: PowerSourceCapabilitiesTrait._PowerSourceCurrentType.ValueType  # 0
        POWER_SOURCE_CURRENT_TYPE_DC: PowerSourceCapabilitiesTrait._PowerSourceCurrentType.ValueType  # 1
        POWER_SOURCE_CURRENT_TYPE_AC: PowerSourceCapabilitiesTrait._PowerSourceCurrentType.ValueType  # 2

    class PowerSourceCurrentType(_PowerSourceCurrentType, metaclass=_PowerSourceCurrentTypeEnumTypeWrapper): ...
    POWER_SOURCE_CURRENT_TYPE_UNSPECIFIED: PowerSourceCapabilitiesTrait.PowerSourceCurrentType.ValueType  # 0
    POWER_SOURCE_CURRENT_TYPE_DC: PowerSourceCapabilitiesTrait.PowerSourceCurrentType.ValueType  # 1
    POWER_SOURCE_CURRENT_TYPE_AC: PowerSourceCapabilitiesTrait.PowerSourceCurrentType.ValueType  # 2

    TYPE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    NOMINALVOLTAGE_FIELD_NUMBER: _builtins.int
    MAXIMUMCURRENT_FIELD_NUMBER: _builtins.int
    CURRENTTYPE_FIELD_NUMBER: _builtins.int
    ORDER_FIELD_NUMBER: _builtins.int
    REMOVABLE_FIELD_NUMBER: _builtins.int
    type: Global___PowerSourceCapabilitiesTrait.PowerSourceType.ValueType
    nominalVoltage: _builtins.float
    currentType: Global___PowerSourceCapabilitiesTrait.PowerSourceCurrentType.ValueType
    order: _builtins.int
    removable: _builtins.bool
    @_builtins.property
    def description(self) -> _common_pb2.StringRef: ...
    @_builtins.property
    def maximumCurrent(self) -> _wrappers_pb2.FloatValue: ...
    def __init__(
        self,
        *,
        type: Global___PowerSourceCapabilitiesTrait.PowerSourceType.ValueType = ...,
        description: _common_pb2.StringRef | None = ...,
        nominalVoltage: _builtins.float = ...,
        maximumCurrent: _wrappers_pb2.FloatValue | None = ...,
        currentType: Global___PowerSourceCapabilitiesTrait.PowerSourceCurrentType.ValueType = ...,
        order: _builtins.int = ...,
        removable: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "maximumCurrent", b"maximumCurrent"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["currentType", b"currentType", "description", b"description", "maximumCurrent", b"maximumCurrent", "nominalVoltage", b"nominalVoltage", "order", b"order", "removable", b"removable", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PowerSourceCapabilitiesTrait: _TypeAlias = PowerSourceCapabilitiesTrait  # noqa: Y015

@_typing.final
class BatteryPowerSourceTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _BatteryReplacementIndicator:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BatteryReplacementIndicatorEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[BatteryPowerSourceTrait._BatteryReplacementIndicator.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        BATTERY_REPLACEMENT_INDICATOR_UNSPECIFIED: BatteryPowerSourceTrait._BatteryReplacementIndicator.ValueType  # 0
        BATTERY_REPLACEMENT_INDICATOR_NOT_AT_ALL: BatteryPowerSourceTrait._BatteryReplacementIndicator.ValueType  # 1
        BATTERY_REPLACEMENT_INDICATOR_SOON: BatteryPowerSourceTrait._BatteryReplacementIndicator.ValueType  # 2
        BATTERY_REPLACEMENT_INDICATOR_IMMEDIATELY: BatteryPowerSourceTrait._BatteryReplacementIndicator.ValueType  # 3

    class BatteryReplacementIndicator(_BatteryReplacementIndicator, metaclass=_BatteryReplacementIndicatorEnumTypeWrapper): ...
    BATTERY_REPLACEMENT_INDICATOR_UNSPECIFIED: BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType  # 0
    BATTERY_REPLACEMENT_INDICATOR_NOT_AT_ALL: BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType  # 1
    BATTERY_REPLACEMENT_INDICATOR_SOON: BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType  # 2
    BATTERY_REPLACEMENT_INDICATOR_IMMEDIATELY: BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType  # 3

    @_typing.final
    class BatteryRemaining(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        REMAININGPERCENT_FIELD_NUMBER: _builtins.int
        REMAININGTIME_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def remainingPercent(self) -> _wrappers_pb2.FloatValue: ...
        @_builtins.property
        def remainingTime(self) -> _common_pb2.Timer: ...
        def __init__(
            self,
            *,
            remainingPercent: _wrappers_pb2.FloatValue | None = ...,
            remainingTime: _common_pb2.Timer | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["remainingPercent", b"remainingPercent", "remainingTime", b"remainingTime"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["remainingPercent", b"remainingPercent", "remainingTime", b"remainingTime"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class BatteryChangedEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CONDITION_FIELD_NUMBER: _builtins.int
        STATUS_FIELD_NUMBER: _builtins.int
        REPLACEMENTINDICATOR_FIELD_NUMBER: _builtins.int
        REMAINING_FIELD_NUMBER: _builtins.int
        condition: Global___PowerSourceTrait.PowerSourceCondition.ValueType
        status: Global___PowerSourceTrait.PowerSourceStatus.ValueType
        replacementIndicator: Global___BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType
        @_builtins.property
        def remaining(self) -> Global___BatteryPowerSourceTrait.BatteryRemaining: ...
        def __init__(
            self,
            *,
            condition: Global___PowerSourceTrait.PowerSourceCondition.ValueType = ...,
            status: Global___PowerSourceTrait.PowerSourceStatus.ValueType = ...,
            replacementIndicator: Global___BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType = ...,
            remaining: Global___BatteryPowerSourceTrait.BatteryRemaining | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["remaining", b"remaining"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["condition", b"condition", "remaining", b"remaining", "replacementIndicator", b"replacementIndicator", "status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TYPE_FIELD_NUMBER: _builtins.int
    ASSESSEDVOLTAGE_FIELD_NUMBER: _builtins.int
    ASSESSEDCURRENT_FIELD_NUMBER: _builtins.int
    ASSESSEDFREQUENCY_FIELD_NUMBER: _builtins.int
    CONDITION_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    PRESENT_FIELD_NUMBER: _builtins.int
    REPLACEMENTINDICATOR_FIELD_NUMBER: _builtins.int
    REMAINING_FIELD_NUMBER: _builtins.int
    type: Global___PowerSourceCapabilitiesTrait.PowerSourceType.ValueType
    condition: Global___PowerSourceTrait.PowerSourceCondition.ValueType
    status: Global___PowerSourceTrait.PowerSourceStatus.ValueType
    present: _builtins.bool
    replacementIndicator: Global___BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType
    @_builtins.property
    def assessedVoltage(self) -> _wrappers_pb2.FloatValue: ...
    @_builtins.property
    def assessedCurrent(self) -> _wrappers_pb2.FloatValue: ...
    @_builtins.property
    def assessedFrequency(self) -> _wrappers_pb2.FloatValue: ...
    @_builtins.property
    def remaining(self) -> Global___BatteryPowerSourceTrait.BatteryRemaining: ...
    def __init__(
        self,
        *,
        type: Global___PowerSourceCapabilitiesTrait.PowerSourceType.ValueType = ...,
        assessedVoltage: _wrappers_pb2.FloatValue | None = ...,
        assessedCurrent: _wrappers_pb2.FloatValue | None = ...,
        assessedFrequency: _wrappers_pb2.FloatValue | None = ...,
        condition: Global___PowerSourceTrait.PowerSourceCondition.ValueType = ...,
        status: Global___PowerSourceTrait.PowerSourceStatus.ValueType = ...,
        present: _builtins.bool = ...,
        replacementIndicator: Global___BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType = ...,
        remaining: Global___BatteryPowerSourceTrait.BatteryRemaining | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["assessedCurrent", b"assessedCurrent", "assessedFrequency", b"assessedFrequency", "assessedVoltage", b"assessedVoltage", "remaining", b"remaining"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["assessedCurrent", b"assessedCurrent", "assessedFrequency", b"assessedFrequency", "assessedVoltage", b"assessedVoltage", "condition", b"condition", "present", b"present", "remaining", b"remaining", "replacementIndicator", b"replacementIndicator", "status", b"status", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BatteryPowerSourceTrait: _TypeAlias = BatteryPowerSourceTrait  # noqa: Y015
