"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from ...weave import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UserPincodesSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _PincodeErrorCodes:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PincodeErrorCodesEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[UserPincodesSettingsTrait._PincodeErrorCodes.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        PINCODE_ERROR_CODES_UNSPECIFIED: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 0
        PINCODE_ERROR_CODES_DUPLICATE_PINCODE: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 1
        PINCODE_ERROR_CODES_TOO_MANY_PINCODES: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 2
        PINCODE_ERROR_CODES_INVALID_PINCODE: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 3
        PINCODE_ERROR_CODES_SUCCESS_PINCODE_DELETED: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 4
        PINCODE_ERROR_CODES_SUCCESS_PINCODE_STATUS: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 5
        PINCODE_ERROR_CODES_DUPLICATE_NONCE: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 6
        PINCODE_ERROR_CODES_EXCEEDED_RATE_LIMIT: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 7

    class PincodeErrorCodes(_PincodeErrorCodes, metaclass=_PincodeErrorCodesEnumTypeWrapper): ...
    PINCODE_ERROR_CODES_UNSPECIFIED: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 0
    PINCODE_ERROR_CODES_DUPLICATE_PINCODE: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 1
    PINCODE_ERROR_CODES_TOO_MANY_PINCODES: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 2
    PINCODE_ERROR_CODES_INVALID_PINCODE: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 3
    PINCODE_ERROR_CODES_SUCCESS_PINCODE_DELETED: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 4
    PINCODE_ERROR_CODES_SUCCESS_PINCODE_STATUS: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 5
    PINCODE_ERROR_CODES_DUPLICATE_NONCE: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 6
    PINCODE_ERROR_CODES_EXCEEDED_RATE_LIMIT: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 7

    class _PincodeChangeReason:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PincodeChangeReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[UserPincodesSettingsTrait._PincodeChangeReason.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        PINCODE_CHANGE_REASON_UNSPECIFIED: UserPincodesSettingsTrait._PincodeChangeReason.ValueType  # 0
        PINCODE_CHANGE_REASON_UPDATE: UserPincodesSettingsTrait._PincodeChangeReason.ValueType  # 1
        PINCODE_CHANGE_REASON_DELETION: UserPincodesSettingsTrait._PincodeChangeReason.ValueType  # 2

    class PincodeChangeReason(_PincodeChangeReason, metaclass=_PincodeChangeReasonEnumTypeWrapper): ...
    PINCODE_CHANGE_REASON_UNSPECIFIED: UserPincodesSettingsTrait.PincodeChangeReason.ValueType  # 0
    PINCODE_CHANGE_REASON_UPDATE: UserPincodesSettingsTrait.PincodeChangeReason.ValueType  # 1
    PINCODE_CHANGE_REASON_DELETION: UserPincodesSettingsTrait.PincodeChangeReason.ValueType  # 2

    @_typing.final
    class UserPincodesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___UserPincodesSettingsTrait.UserPincode: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___UserPincodesSettingsTrait.UserPincode | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class UserPincode(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USERID_FIELD_NUMBER: _builtins.int
        PINCODE_FIELD_NUMBER: _builtins.int
        PINCODECREDENTIALENABLED_FIELD_NUMBER: _builtins.int
        pincode: _builtins.bytes
        @_builtins.property
        def userId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def pincodeCredentialEnabled(self) -> _wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            userId: _common_pb2.ResourceId | None = ...,
            pincode: _builtins.bytes = ...,
            pincodeCredentialEnabled: _wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["pincodeCredentialEnabled", b"pincodeCredentialEnabled", "userId", b"userId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["pincode", b"pincode", "pincodeCredentialEnabled", b"pincodeCredentialEnabled", "userId", b"userId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SetUserPincodeRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USERPINCODE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def userPincode(self) -> Global___UserPincodesSettingsTrait.UserPincode: ...
        def __init__(
            self,
            *,
            userPincode: Global___UserPincodesSettingsTrait.UserPincode | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["userPincode", b"userPincode"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["userPincode", b"userPincode"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SetUserPincodeResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___UserPincodesSettingsTrait.PincodeErrorCodes.ValueType
        def __init__(
            self,
            *,
            status: Global___UserPincodesSettingsTrait.PincodeErrorCodes.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class GetUserPincodeRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USERID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def userId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            userId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["userId", b"userId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["userId", b"userId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class GetUserPincodeResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USERPINCODE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def userPincode(self) -> Global___UserPincodesSettingsTrait.UserPincode: ...
        def __init__(
            self,
            *,
            userPincode: Global___UserPincodesSettingsTrait.UserPincode | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["userPincode", b"userPincode"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["userPincode", b"userPincode"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class DeleteUserPincodeRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USERID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def userId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            userId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["userId", b"userId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["userId", b"userId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class DeleteUserPincodeResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___UserPincodesSettingsTrait.PincodeErrorCodes.ValueType
        def __init__(
            self,
            *,
            status: Global___UserPincodesSettingsTrait.PincodeErrorCodes.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class UserPincodeChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USERID_FIELD_NUMBER: _builtins.int
        REASON_FIELD_NUMBER: _builtins.int
        reason: Global___UserPincodesSettingsTrait.PincodeChangeReason.ValueType
        @_builtins.property
        def userId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            userId: _common_pb2.ResourceId | None = ...,
            reason: Global___UserPincodesSettingsTrait.PincodeChangeReason.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["userId", b"userId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["reason", b"reason", "userId", b"userId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    USERPINCODES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def userPincodes(self) -> _containers.MessageMap[_builtins.int, Global___UserPincodesSettingsTrait.UserPincode]: ...
    def __init__(
        self,
        *,
        userPincodes: _abc.Mapping[_builtins.int, Global___UserPincodesSettingsTrait.UserPincode] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["userPincodes", b"userPincodes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserPincodesSettingsTrait: _TypeAlias = UserPincodesSettingsTrait  # noqa: Y015

@_typing.final
class BoltLockTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _BoltState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BoltStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[BoltLockTrait._BoltState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        BOLT_STATE_UNSPECIFIED: BoltLockTrait._BoltState.ValueType  # 0
        BOLT_STATE_RETRACTED: BoltLockTrait._BoltState.ValueType  # 1
        BOLT_STATE_EXTENDED: BoltLockTrait._BoltState.ValueType  # 2

    class BoltState(_BoltState, metaclass=_BoltStateEnumTypeWrapper): ...
    BOLT_STATE_UNSPECIFIED: BoltLockTrait.BoltState.ValueType  # 0
    BOLT_STATE_RETRACTED: BoltLockTrait.BoltState.ValueType  # 1
    BOLT_STATE_EXTENDED: BoltLockTrait.BoltState.ValueType  # 2

    class _BoltLockActorMethod:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BoltLockActorMethodEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[BoltLockTrait._BoltLockActorMethod.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        BOLT_LOCK_ACTOR_METHOD_UNSPECIFIED: BoltLockTrait._BoltLockActorMethod.ValueType  # 0
        BOLT_LOCK_ACTOR_METHOD_OTHER: BoltLockTrait._BoltLockActorMethod.ValueType  # 1
        BOLT_LOCK_ACTOR_METHOD_PHYSICAL: BoltLockTrait._BoltLockActorMethod.ValueType  # 2
        BOLT_LOCK_ACTOR_METHOD_KEYPAD_PIN: BoltLockTrait._BoltLockActorMethod.ValueType  # 3
        BOLT_LOCK_ACTOR_METHOD_LOCAL_IMPLICIT: BoltLockTrait._BoltLockActorMethod.ValueType  # 4
        BOLT_LOCK_ACTOR_METHOD_REMOTE_USER_EXPLICIT: BoltLockTrait._BoltLockActorMethod.ValueType  # 5
        BOLT_LOCK_ACTOR_METHOD_REMOTE_USER_IMPLICIT: BoltLockTrait._BoltLockActorMethod.ValueType  # 6
        BOLT_LOCK_ACTOR_METHOD_REMOTE_USER_OTHER: BoltLockTrait._BoltLockActorMethod.ValueType  # 7
        BOLT_LOCK_ACTOR_METHOD_REMOTE_DELEGATE: BoltLockTrait._BoltLockActorMethod.ValueType  # 8
        BOLT_LOCK_ACTOR_METHOD_LOW_POWER_SHUTDOWN: BoltLockTrait._BoltLockActorMethod.ValueType  # 9
        BOLT_LOCK_ACTOR_METHOD_VOICE_ASSISTANT: BoltLockTrait._BoltLockActorMethod.ValueType  # 10

    class BoltLockActorMethod(_BoltLockActorMethod, metaclass=_BoltLockActorMethodEnumTypeWrapper): ...
    BOLT_LOCK_ACTOR_METHOD_UNSPECIFIED: BoltLockTrait.BoltLockActorMethod.ValueType  # 0
    BOLT_LOCK_ACTOR_METHOD_OTHER: BoltLockTrait.BoltLockActorMethod.ValueType  # 1
    BOLT_LOCK_ACTOR_METHOD_PHYSICAL: BoltLockTrait.BoltLockActorMethod.ValueType  # 2
    BOLT_LOCK_ACTOR_METHOD_KEYPAD_PIN: BoltLockTrait.BoltLockActorMethod.ValueType  # 3
    BOLT_LOCK_ACTOR_METHOD_LOCAL_IMPLICIT: BoltLockTrait.BoltLockActorMethod.ValueType  # 4
    BOLT_LOCK_ACTOR_METHOD_REMOTE_USER_EXPLICIT: BoltLockTrait.BoltLockActorMethod.ValueType  # 5
    BOLT_LOCK_ACTOR_METHOD_REMOTE_USER_IMPLICIT: BoltLockTrait.BoltLockActorMethod.ValueType  # 6
    BOLT_LOCK_ACTOR_METHOD_REMOTE_USER_OTHER: BoltLockTrait.BoltLockActorMethod.ValueType  # 7
    BOLT_LOCK_ACTOR_METHOD_REMOTE_DELEGATE: BoltLockTrait.BoltLockActorMethod.ValueType  # 8
    BOLT_LOCK_ACTOR_METHOD_LOW_POWER_SHUTDOWN: BoltLockTrait.BoltLockActorMethod.ValueType  # 9
    BOLT_LOCK_ACTOR_METHOD_VOICE_ASSISTANT: BoltLockTrait.BoltLockActorMethod.ValueType  # 10

    class _BoltActuatorState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BoltActuatorStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[BoltLockTrait._BoltActuatorState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        BOLT_ACTUATOR_STATE_UNSPECIFIED: BoltLockTrait._BoltActuatorState.ValueType  # 0
        BOLT_ACTUATOR_STATE_OK: BoltLockTrait._BoltActuatorState.ValueType  # 1
        BOLT_ACTUATOR_STATE_LOCKING: BoltLockTrait._BoltActuatorState.ValueType  # 2
        BOLT_ACTUATOR_STATE_UNLOCKING: BoltLockTrait._BoltActuatorState.ValueType  # 3
        BOLT_ACTUATOR_STATE_MOVING: BoltLockTrait._BoltActuatorState.ValueType  # 4
        BOLT_ACTUATOR_STATE_JAMMED_LOCKING: BoltLockTrait._BoltActuatorState.ValueType  # 5
        BOLT_ACTUATOR_STATE_JAMMED_UNLOCKING: BoltLockTrait._BoltActuatorState.ValueType  # 6
        BOLT_ACTUATOR_STATE_JAMMED_OTHER: BoltLockTrait._BoltActuatorState.ValueType  # 7

    class BoltActuatorState(_BoltActuatorState, metaclass=_BoltActuatorStateEnumTypeWrapper): ...
    BOLT_ACTUATOR_STATE_UNSPECIFIED: BoltLockTrait.BoltActuatorState.ValueType  # 0
    BOLT_ACTUATOR_STATE_OK: BoltLockTrait.BoltActuatorState.ValueType  # 1
    BOLT_ACTUATOR_STATE_LOCKING: BoltLockTrait.BoltActuatorState.ValueType  # 2
    BOLT_ACTUATOR_STATE_UNLOCKING: BoltLockTrait.BoltActuatorState.ValueType  # 3
    BOLT_ACTUATOR_STATE_MOVING: BoltLockTrait.BoltActuatorState.ValueType  # 4
    BOLT_ACTUATOR_STATE_JAMMED_LOCKING: BoltLockTrait.BoltActuatorState.ValueType  # 5
    BOLT_ACTUATOR_STATE_JAMMED_UNLOCKING: BoltLockTrait.BoltActuatorState.ValueType  # 6
    BOLT_ACTUATOR_STATE_JAMMED_OTHER: BoltLockTrait.BoltActuatorState.ValueType  # 7

    class _BoltLockedState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BoltLockedStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[BoltLockTrait._BoltLockedState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        BOLT_LOCKED_STATE_UNSPECIFIED: BoltLockTrait._BoltLockedState.ValueType  # 0
        BOLT_LOCKED_STATE_UNLOCKED: BoltLockTrait._BoltLockedState.ValueType  # 1
        BOLT_LOCKED_STATE_LOCKED: BoltLockTrait._BoltLockedState.ValueType  # 2
        BOLT_LOCKED_STATE_UNKNOWN: BoltLockTrait._BoltLockedState.ValueType  # 3

    class BoltLockedState(_BoltLockedState, metaclass=_BoltLockedStateEnumTypeWrapper): ...
    BOLT_LOCKED_STATE_UNSPECIFIED: BoltLockTrait.BoltLockedState.ValueType  # 0
    BOLT_LOCKED_STATE_UNLOCKED: BoltLockTrait.BoltLockedState.ValueType  # 1
    BOLT_LOCKED_STATE_LOCKED: BoltLockTrait.BoltLockedState.ValueType  # 2
    BOLT_LOCKED_STATE_UNKNOWN: BoltLockTrait.BoltLockedState.ValueType  # 3

    @_typing.final
    class BoltLockActorStruct(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        METHOD_FIELD_NUMBER: _builtins.int
        ORIGINATOR_FIELD_NUMBER: _builtins.int
        AGENT_FIELD_NUMBER: _builtins.int
        method: Global___BoltLockTrait.BoltLockActorMethod.ValueType
        @_builtins.property
        def originator(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def agent(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            method: Global___BoltLockTrait.BoltLockActorMethod.ValueType = ...,
            originator: _common_pb2.ResourceId | None = ...,
            agent: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["agent", b"agent", "originator", b"originator"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["agent", b"agent", "method", b"method", "originator", b"originator"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class BoltLockChangeRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATE_FIELD_NUMBER: _builtins.int
        BOLTLOCKACTOR_FIELD_NUMBER: _builtins.int
        state: Global___BoltLockTrait.BoltState.ValueType
        @_builtins.property
        def boltLockActor(self) -> Global___BoltLockTrait.BoltLockActorStruct: ...
        def __init__(
            self,
            *,
            state: Global___BoltLockTrait.BoltState.ValueType = ...,
            boltLockActor: Global___BoltLockTrait.BoltLockActorStruct | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["boltLockActor", b"boltLockActor"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["boltLockActor", b"boltLockActor", "state", b"state"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class BoltLockProximityChangeRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATE_FIELD_NUMBER: _builtins.int
        BOLTLOCKACTOR_FIELD_NUMBER: _builtins.int
        TOKEN_FIELD_NUMBER: _builtins.int
        state: Global___BoltLockTrait.BoltState.ValueType
        token: _builtins.bytes
        @_builtins.property
        def boltLockActor(self) -> Global___BoltLockTrait.BoltLockActorStruct: ...
        def __init__(
            self,
            *,
            state: Global___BoltLockTrait.BoltState.ValueType = ...,
            boltLockActor: Global___BoltLockTrait.BoltLockActorStruct | None = ...,
            token: _builtins.bytes = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["boltLockActor", b"boltLockActor"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["boltLockActor", b"boltLockActor", "state", b"state", "token", b"token"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class BoltActuatorStateChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATE_FIELD_NUMBER: _builtins.int
        ACTUATORSTATE_FIELD_NUMBER: _builtins.int
        LOCKEDSTATE_FIELD_NUMBER: _builtins.int
        BOLTLOCKACTOR_FIELD_NUMBER: _builtins.int
        state: Global___BoltLockTrait.BoltState.ValueType
        actuatorState: Global___BoltLockTrait.BoltActuatorState.ValueType
        lockedState: Global___BoltLockTrait.BoltLockedState.ValueType
        @_builtins.property
        def boltLockActor(self) -> Global___BoltLockTrait.BoltLockActorStruct: ...
        def __init__(
            self,
            *,
            state: Global___BoltLockTrait.BoltState.ValueType = ...,
            actuatorState: Global___BoltLockTrait.BoltActuatorState.ValueType = ...,
            lockedState: Global___BoltLockTrait.BoltLockedState.ValueType = ...,
            boltLockActor: Global___BoltLockTrait.BoltLockActorStruct | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["boltLockActor", b"boltLockActor"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["actuatorState", b"actuatorState", "boltLockActor", b"boltLockActor", "lockedState", b"lockedState", "state", b"state"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    STATE_FIELD_NUMBER: _builtins.int
    ACTUATORSTATE_FIELD_NUMBER: _builtins.int
    LOCKEDSTATE_FIELD_NUMBER: _builtins.int
    BOLTLOCKACTOR_FIELD_NUMBER: _builtins.int
    LOCKEDSTATELASTCHANGEDAT_FIELD_NUMBER: _builtins.int
    state: Global___BoltLockTrait.BoltState.ValueType
    actuatorState: Global___BoltLockTrait.BoltActuatorState.ValueType
    lockedState: Global___BoltLockTrait.BoltLockedState.ValueType
    @_builtins.property
    def boltLockActor(self) -> Global___BoltLockTrait.BoltLockActorStruct: ...
    @_builtins.property
    def lockedStateLastChangedAt(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        state: Global___BoltLockTrait.BoltState.ValueType = ...,
        actuatorState: Global___BoltLockTrait.BoltActuatorState.ValueType = ...,
        lockedState: Global___BoltLockTrait.BoltLockedState.ValueType = ...,
        boltLockActor: Global___BoltLockTrait.BoltLockActorStruct | None = ...,
        lockedStateLastChangedAt: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["boltLockActor", b"boltLockActor", "lockedStateLastChangedAt", b"lockedStateLastChangedAt"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actuatorState", b"actuatorState", "boltLockActor", b"boltLockActor", "lockedState", b"lockedState", "lockedStateLastChangedAt", b"lockedStateLastChangedAt", "state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BoltLockTrait: _TypeAlias = BoltLockTrait  # noqa: Y015

@_typing.final
class SensorAssociationTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _StatusCode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SensorAssociationTrait._StatusCode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATUS_CODE_UNSPECIFIED: SensorAssociationTrait._StatusCode.ValueType  # 0
        STATUS_CODE_SUCCESS: SensorAssociationTrait._StatusCode.ValueType  # 1
        STATUS_CODE_FAILURE: SensorAssociationTrait._StatusCode.ValueType  # 2
        STATUS_CODE_SENSOR_ALREADY_ASSOCIATED_OTHER: SensorAssociationTrait._StatusCode.ValueType  # 3
        STATUS_CODE_SENSOR_ALREADY_ASSOCIATED_SELF: SensorAssociationTrait._StatusCode.ValueType  # 4
        STATUS_CODE_SENSOR_INVALID: SensorAssociationTrait._StatusCode.ValueType  # 5
        STATUS_CODE_USER_SETTING_INVALID: SensorAssociationTrait._StatusCode.ValueType  # 6

    class StatusCode(_StatusCode, metaclass=_StatusCodeEnumTypeWrapper): ...
    STATUS_CODE_UNSPECIFIED: SensorAssociationTrait.StatusCode.ValueType  # 0
    STATUS_CODE_SUCCESS: SensorAssociationTrait.StatusCode.ValueType  # 1
    STATUS_CODE_FAILURE: SensorAssociationTrait.StatusCode.ValueType  # 2
    STATUS_CODE_SENSOR_ALREADY_ASSOCIATED_OTHER: SensorAssociationTrait.StatusCode.ValueType  # 3
    STATUS_CODE_SENSOR_ALREADY_ASSOCIATED_SELF: SensorAssociationTrait.StatusCode.ValueType  # 4
    STATUS_CODE_SENSOR_INVALID: SensorAssociationTrait.StatusCode.ValueType  # 5
    STATUS_CODE_USER_SETTING_INVALID: SensorAssociationTrait.StatusCode.ValueType  # 6

    class _SensorAssociationStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SensorAssociationStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SensorAssociationTrait._SensorAssociationStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SENSOR_ASSOCIATION_STATUS_UNSPECIFIED: SensorAssociationTrait._SensorAssociationStatus.ValueType  # 0
        SENSOR_ASSOCIATION_STATUS_ASSOCIATED_SELF: SensorAssociationTrait._SensorAssociationStatus.ValueType  # 1
        SENSOR_ASSOCIATION_STATUS_ASSOCIATED_OTHER: SensorAssociationTrait._SensorAssociationStatus.ValueType  # 2
        SENSOR_ASSOCIATION_STATUS_DEFAULT: SensorAssociationTrait._SensorAssociationStatus.ValueType  # 3
        SENSOR_ASSOCIATION_STATUS_ELIGIBLE: SensorAssociationTrait._SensorAssociationStatus.ValueType  # 4
        SENSOR_ASSOCIATION_STATUS_INELIGIBLE: SensorAssociationTrait._SensorAssociationStatus.ValueType  # 5

    class SensorAssociationStatus(_SensorAssociationStatus, metaclass=_SensorAssociationStatusEnumTypeWrapper): ...
    SENSOR_ASSOCIATION_STATUS_UNSPECIFIED: SensorAssociationTrait.SensorAssociationStatus.ValueType  # 0
    SENSOR_ASSOCIATION_STATUS_ASSOCIATED_SELF: SensorAssociationTrait.SensorAssociationStatus.ValueType  # 1
    SENSOR_ASSOCIATION_STATUS_ASSOCIATED_OTHER: SensorAssociationTrait.SensorAssociationStatus.ValueType  # 2
    SENSOR_ASSOCIATION_STATUS_DEFAULT: SensorAssociationTrait.SensorAssociationStatus.ValueType  # 3
    SENSOR_ASSOCIATION_STATUS_ELIGIBLE: SensorAssociationTrait.SensorAssociationStatus.ValueType  # 4
    SENSOR_ASSOCIATION_STATUS_INELIGIBLE: SensorAssociationTrait.SensorAssociationStatus.ValueType  # 5

    @_typing.final
    class SetUserSensorAssociationRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SENSORDEVICEID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sensorDeviceId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            sensorDeviceId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sensorDeviceId", b"sensorDeviceId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sensorDeviceId", b"sensorDeviceId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SetUserSensorAssociationResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___SensorAssociationTrait.StatusCode.ValueType
        def __init__(
            self,
            *,
            status: Global___SensorAssociationTrait.StatusCode.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SensorDeviceStatus(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        DEVICEID_FIELD_NUMBER: _builtins.int
        SENSORASSOCIATIONSTATUS_FIELD_NUMBER: _builtins.int
        SENSORASSOCIATIONSTATUSLIST_FIELD_NUMBER: _builtins.int
        sensorAssociationStatus: Global___SensorAssociationTrait.SensorAssociationStatus.ValueType
        @_builtins.property
        def deviceId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def sensorAssociationStatusList(self) -> _containers.RepeatedScalarFieldContainer[Global___SensorAssociationTrait.SensorAssociationStatus.ValueType]: ...
        def __init__(
            self,
            *,
            deviceId: _common_pb2.ResourceId | None = ...,
            sensorAssociationStatus: Global___SensorAssociationTrait.SensorAssociationStatus.ValueType = ...,
            sensorAssociationStatusList: _abc.Iterable[Global___SensorAssociationTrait.SensorAssociationStatus.ValueType] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["deviceId", b"deviceId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["deviceId", b"deviceId", "sensorAssociationStatus", b"sensorAssociationStatus", "sensorAssociationStatusList", b"sensorAssociationStatusList"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SENSORS_FIELD_NUMBER: _builtins.int
    ASSOCIATEDSENSORDEVICEID_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sensors(self) -> _containers.RepeatedCompositeFieldContainer[Global___SensorAssociationTrait.SensorDeviceStatus]: ...
    @_builtins.property
    def associatedSensorDeviceId(self) -> _common_pb2.ResourceId: ...
    def __init__(
        self,
        *,
        sensors: _abc.Iterable[Global___SensorAssociationTrait.SensorDeviceStatus] | None = ...,
        associatedSensorDeviceId: _common_pb2.ResourceId | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["associatedSensorDeviceId", b"associatedSensorDeviceId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["associatedSensorDeviceId", b"associatedSensorDeviceId", "sensors", b"sensors"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SensorAssociationTrait: _TypeAlias = SensorAssociationTrait  # noqa: Y015

@_typing.final
class UserNFCTokenManagementTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _NFCTokenEvent:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _NFCTokenEventEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[UserNFCTokenManagementTrait._NFCTokenEvent.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NFC_TOKEN_EVENT_UNSPECIFIED: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 0
        NFC_TOKEN_EVENT_PAIRED: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 1
        NFC_TOKEN_EVENT_UNPAIRED: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 2
        NFC_TOKEN_EVENT_STRUCTURE_AUTH: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 3
        NFC_TOKEN_EVENT_STRUCTURE_UNAUTH: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 4
        NFC_TOKEN_EVENT_TRANSFERRED: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 5
        NFC_TOKEN_EVENT_DISABLED: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 6
        NFC_TOKEN_EVENT_ENABLED: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 7

    class NFCTokenEvent(_NFCTokenEvent, metaclass=_NFCTokenEventEnumTypeWrapper): ...
    NFC_TOKEN_EVENT_UNSPECIFIED: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 0
    NFC_TOKEN_EVENT_PAIRED: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 1
    NFC_TOKEN_EVENT_UNPAIRED: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 2
    NFC_TOKEN_EVENT_STRUCTURE_AUTH: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 3
    NFC_TOKEN_EVENT_STRUCTURE_UNAUTH: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 4
    NFC_TOKEN_EVENT_TRANSFERRED: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 5
    NFC_TOKEN_EVENT_DISABLED: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 6
    NFC_TOKEN_EVENT_ENABLED: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 7

    @_typing.final
    class TransferUserNFCTokenRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TARGETUSERID_FIELD_NUMBER: _builtins.int
        TOKENDEVICEID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def targetUserId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def tokenDeviceId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            targetUserId: _common_pb2.ResourceId | None = ...,
            tokenDeviceId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["targetUserId", b"targetUserId", "tokenDeviceId", b"tokenDeviceId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["targetUserId", b"targetUserId", "tokenDeviceId", b"tokenDeviceId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SetUserNFCTokenEnableStateRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TOKENDEVICEID_FIELD_NUMBER: _builtins.int
        ENABLED_FIELD_NUMBER: _builtins.int
        enabled: _builtins.bool
        @_builtins.property
        def tokenDeviceId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            tokenDeviceId: _common_pb2.ResourceId | None = ...,
            enabled: _builtins.bool = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["tokenDeviceId", b"tokenDeviceId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "tokenDeviceId", b"tokenDeviceId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AuthUserNFCTokenToStructureRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TOKENDEVICEID_FIELD_NUMBER: _builtins.int
        AUTHORIZED_FIELD_NUMBER: _builtins.int
        STRUCTUREID_FIELD_NUMBER: _builtins.int
        authorized: _builtins.bool
        @_builtins.property
        def tokenDeviceId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def structureId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            tokenDeviceId: _common_pb2.ResourceId | None = ...,
            authorized: _builtins.bool = ...,
            structureId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["structureId", b"structureId", "tokenDeviceId", b"tokenDeviceId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["authorized", b"authorized", "structureId", b"structureId", "tokenDeviceId", b"tokenDeviceId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class UserNFCTokenManagementEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        NFCTOKENMANAGEMENTEVENT_FIELD_NUMBER: _builtins.int
        USERNFCTOKEN_FIELD_NUMBER: _builtins.int
        INITIATINGUSERID_FIELD_NUMBER: _builtins.int
        PREVIOUSUSERID_FIELD_NUMBER: _builtins.int
        nfcTokenManagementEvent: Global___UserNFCTokenManagementTrait.NFCTokenEvent.ValueType
        @_builtins.property
        def userNfcToken(self) -> Global___UserNFCTokensTrait.UserNFCTokenData: ...
        @_builtins.property
        def initiatingUserId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def previousUserId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            nfcTokenManagementEvent: Global___UserNFCTokenManagementTrait.NFCTokenEvent.ValueType = ...,
            userNfcToken: Global___UserNFCTokensTrait.UserNFCTokenData | None = ...,
            initiatingUserId: _common_pb2.ResourceId | None = ...,
            previousUserId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["initiatingUserId", b"initiatingUserId", "previousUserId", b"previousUserId", "userNfcToken", b"userNfcToken"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["initiatingUserId", b"initiatingUserId", "nfcTokenManagementEvent", b"nfcTokenManagementEvent", "previousUserId", b"previousUserId", "userNfcToken", b"userNfcToken"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___UserNFCTokenManagementTrait: _TypeAlias = UserNFCTokenManagementTrait  # noqa: Y015

@_typing.final
class PincodeInputTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _PincodeEntryResult:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PincodeEntryResultEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[PincodeInputTrait._PincodeEntryResult.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        PINCODE_ENTRY_RESULT_UNSPECIFIED: PincodeInputTrait._PincodeEntryResult.ValueType  # 0
        PINCODE_ENTRY_RESULT_FAILURE_INVALID_PINCODE: PincodeInputTrait._PincodeEntryResult.ValueType  # 1
        PINCODE_ENTRY_RESULT_FAILURE_OUT_OF_SCHEDULE: PincodeInputTrait._PincodeEntryResult.ValueType  # 2
        PINCODE_ENTRY_RESULT_FAILURE_PINCODE_DISABLED: PincodeInputTrait._PincodeEntryResult.ValueType  # 3
        PINCODE_ENTRY_RESULT_SUCCESS: PincodeInputTrait._PincodeEntryResult.ValueType  # 4

    class PincodeEntryResult(_PincodeEntryResult, metaclass=_PincodeEntryResultEnumTypeWrapper): ...
    PINCODE_ENTRY_RESULT_UNSPECIFIED: PincodeInputTrait.PincodeEntryResult.ValueType  # 0
    PINCODE_ENTRY_RESULT_FAILURE_INVALID_PINCODE: PincodeInputTrait.PincodeEntryResult.ValueType  # 1
    PINCODE_ENTRY_RESULT_FAILURE_OUT_OF_SCHEDULE: PincodeInputTrait.PincodeEntryResult.ValueType  # 2
    PINCODE_ENTRY_RESULT_FAILURE_PINCODE_DISABLED: PincodeInputTrait.PincodeEntryResult.ValueType  # 3
    PINCODE_ENTRY_RESULT_SUCCESS: PincodeInputTrait.PincodeEntryResult.ValueType  # 4

    class _PincodeInputState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PincodeInputStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[PincodeInputTrait._PincodeInputState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        PINCODE_INPUT_STATE_UNSPECIFIED: PincodeInputTrait._PincodeInputState.ValueType  # 0
        PINCODE_INPUT_STATE_ENABLED: PincodeInputTrait._PincodeInputState.ValueType  # 1
        PINCODE_INPUT_STATE_DISABLED: PincodeInputTrait._PincodeInputState.ValueType  # 2

    class PincodeInputState(_PincodeInputState, metaclass=_PincodeInputStateEnumTypeWrapper): ...
    PINCODE_INPUT_STATE_UNSPECIFIED: PincodeInputTrait.PincodeInputState.ValueType  # 0
    PINCODE_INPUT_STATE_ENABLED: PincodeInputTrait.PincodeInputState.ValueType  # 1
    PINCODE_INPUT_STATE_DISABLED: PincodeInputTrait.PincodeInputState.ValueType  # 2

    @_typing.final
    class KeypadEntryEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PINCODECREDENTIALENABLED_FIELD_NUMBER: _builtins.int
        USERID_FIELD_NUMBER: _builtins.int
        INVALIDENTRYCOUNT_FIELD_NUMBER: _builtins.int
        PINCODEENTRYRESULT_FIELD_NUMBER: _builtins.int
        invalidEntryCount: _builtins.int
        pincodeEntryResult: Global___PincodeInputTrait.PincodeEntryResult.ValueType
        @_builtins.property
        def pincodeCredentialEnabled(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def userId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            pincodeCredentialEnabled: _wrappers_pb2.BoolValue | None = ...,
            userId: _common_pb2.ResourceId | None = ...,
            invalidEntryCount: _builtins.int = ...,
            pincodeEntryResult: Global___PincodeInputTrait.PincodeEntryResult.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["pincodeCredentialEnabled", b"pincodeCredentialEnabled", "userId", b"userId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["invalidEntryCount", b"invalidEntryCount", "pincodeCredentialEnabled", b"pincodeCredentialEnabled", "pincodeEntryResult", b"pincodeEntryResult", "userId", b"userId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class PincodeInputStateChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PINCODEINPUTSTATE_FIELD_NUMBER: _builtins.int
        USERID_FIELD_NUMBER: _builtins.int
        pincodeInputState: Global___PincodeInputTrait.PincodeInputState.ValueType
        @_builtins.property
        def userId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            pincodeInputState: Global___PincodeInputTrait.PincodeInputState.ValueType = ...,
            userId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["userId", b"userId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["pincodeInputState", b"pincodeInputState", "userId", b"userId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PINCODEINPUTSTATE_FIELD_NUMBER: _builtins.int
    pincodeInputState: Global___PincodeInputTrait.PincodeInputState.ValueType
    def __init__(
        self,
        *,
        pincodeInputState: Global___PincodeInputTrait.PincodeInputState.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pincodeInputState", b"pincodeInputState"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PincodeInputTrait: _TypeAlias = PincodeInputTrait  # noqa: Y015

@_typing.final
class TamperTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _TamperState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TamperStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TamperTrait._TamperState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        TAMPER_STATE_UNSPECIFIED: TamperTrait._TamperState.ValueType  # 0
        TAMPER_STATE_CLEAR: TamperTrait._TamperState.ValueType  # 1
        TAMPER_STATE_TAMPERED: TamperTrait._TamperState.ValueType  # 2
        TAMPER_STATE_UNKNOWN: TamperTrait._TamperState.ValueType  # 3

    class TamperState(_TamperState, metaclass=_TamperStateEnumTypeWrapper): ...
    TAMPER_STATE_UNSPECIFIED: TamperTrait.TamperState.ValueType  # 0
    TAMPER_STATE_CLEAR: TamperTrait.TamperState.ValueType  # 1
    TAMPER_STATE_TAMPERED: TamperTrait.TamperState.ValueType  # 2
    TAMPER_STATE_UNKNOWN: TamperTrait.TamperState.ValueType  # 3

    class _TamperStateChangeReason:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TamperStateChangeReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TamperTrait._TamperStateChangeReason.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        TAMPER_STATE_CHANGE_REASON_UNSPECIFIED: TamperTrait._TamperStateChangeReason.ValueType  # 0
        TAMPER_STATE_CHANGE_REASON_CLEAR_SECURE: TamperTrait._TamperStateChangeReason.ValueType  # 1
        TAMPER_STATE_CHANGE_REASON_CLEAR_DISARM: TamperTrait._TamperStateChangeReason.ValueType  # 2
        TAMPER_STATE_CHANGE_REASON_CLEAR_SNOOZE: TamperTrait._TamperStateChangeReason.ValueType  # 3

    class TamperStateChangeReason(_TamperStateChangeReason, metaclass=_TamperStateChangeReasonEnumTypeWrapper): ...
    TAMPER_STATE_CHANGE_REASON_UNSPECIFIED: TamperTrait.TamperStateChangeReason.ValueType  # 0
    TAMPER_STATE_CHANGE_REASON_CLEAR_SECURE: TamperTrait.TamperStateChangeReason.ValueType  # 1
    TAMPER_STATE_CHANGE_REASON_CLEAR_DISARM: TamperTrait.TamperStateChangeReason.ValueType  # 2
    TAMPER_STATE_CHANGE_REASON_CLEAR_SNOOZE: TamperTrait.TamperStateChangeReason.ValueType  # 3

    @_typing.final
    class ResetTamperRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @_typing.final
    class TamperStateChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TAMPERSTATE_FIELD_NUMBER: _builtins.int
        PRIORTAMPERSTATE_FIELD_NUMBER: _builtins.int
        REASON_FIELD_NUMBER: _builtins.int
        TAMPERSTATECHANGETIME_FIELD_NUMBER: _builtins.int
        tamperState: Global___TamperTrait.TamperState.ValueType
        priorTamperState: Global___TamperTrait.TamperState.ValueType
        reason: Global___TamperTrait.TamperStateChangeReason.ValueType
        @_builtins.property
        def tamperStateChangeTime(self) -> _timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            tamperState: Global___TamperTrait.TamperState.ValueType = ...,
            priorTamperState: Global___TamperTrait.TamperState.ValueType = ...,
            reason: Global___TamperTrait.TamperStateChangeReason.ValueType = ...,
            tamperStateChangeTime: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["tamperStateChangeTime", b"tamperStateChangeTime"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["priorTamperState", b"priorTamperState", "reason", b"reason", "tamperState", b"tamperState", "tamperStateChangeTime", b"tamperStateChangeTime"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TAMPERSTATE_FIELD_NUMBER: _builtins.int
    FIRSTOBSERVEDAT_FIELD_NUMBER: _builtins.int
    FIRSTOBSERVEDATMS_FIELD_NUMBER: _builtins.int
    tamperState: Global___TamperTrait.TamperState.ValueType
    @_builtins.property
    def firstObservedAt(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def firstObservedAtMs(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        tamperState: Global___TamperTrait.TamperState.ValueType = ...,
        firstObservedAt: _timestamp_pb2.Timestamp | None = ...,
        firstObservedAtMs: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["firstObservedAt", b"firstObservedAt", "firstObservedAtMs", b"firstObservedAtMs"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["firstObservedAt", b"firstObservedAt", "firstObservedAtMs", b"firstObservedAtMs", "tamperState", b"tamperState"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TamperTrait: _TypeAlias = TamperTrait  # noqa: Y015

@_typing.final
class UserNFCTokenAccessTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _UserNFCTokenAccessResult:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _UserNFCTokenAccessResultEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        USER_NFC_TOKEN_ACCESS_RESULT_UNSPECIFIED: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 0
        USER_NFC_TOKEN_ACCESS_RESULT_SUCCESS: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 1
        USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_UNKNOWN_TOKEN: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 2
        USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_INVALID_TOKEN: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 3
        USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_OUT_OF_SCHEDULE: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 4
        USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_TOKEN_DISABLED: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 5
        USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_INVALID_VERSION: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 6
        USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_OTHER_REASON: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 7

    class UserNFCTokenAccessResult(_UserNFCTokenAccessResult, metaclass=_UserNFCTokenAccessResultEnumTypeWrapper): ...
    USER_NFC_TOKEN_ACCESS_RESULT_UNSPECIFIED: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 0
    USER_NFC_TOKEN_ACCESS_RESULT_SUCCESS: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 1
    USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_UNKNOWN_TOKEN: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 2
    USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_INVALID_TOKEN: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 3
    USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_OUT_OF_SCHEDULE: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 4
    USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_TOKEN_DISABLED: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 5
    USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_INVALID_VERSION: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 6
    USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_OTHER_REASON: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 7

    @_typing.final
    class UserNFCTokenAccessEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        RESULT_FIELD_NUMBER: _builtins.int
        TOKENID_FIELD_NUMBER: _builtins.int
        USERID_FIELD_NUMBER: _builtins.int
        result: Global___UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType
        @_builtins.property
        def tokenId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def userId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            result: Global___UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType = ...,
            tokenId: _common_pb2.ResourceId | None = ...,
            userId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["tokenId", b"tokenId", "userId", b"userId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "tokenId", b"tokenId", "userId", b"userId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___UserNFCTokenAccessTrait: _TypeAlias = UserNFCTokenAccessTrait  # noqa: Y015

@_typing.final
class UserNFCTokensTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class UserNFCTokenData(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USERID_FIELD_NUMBER: _builtins.int
        TOKENDEVICEID_FIELD_NUMBER: _builtins.int
        ENABLED_FIELD_NUMBER: _builtins.int
        STRUCTUREIDS_FIELD_NUMBER: _builtins.int
        LABEL_FIELD_NUMBER: _builtins.int
        METADATA_FIELD_NUMBER: _builtins.int
        enabled: _builtins.bool
        label: _builtins.str
        @_builtins.property
        def userId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def tokenDeviceId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def structureIds(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.ResourceId]: ...
        @_builtins.property
        def metadata(self) -> Global___UserNFCTokenMetadataTrait.Metadata: ...
        def __init__(
            self,
            *,
            userId: _common_pb2.ResourceId | None = ...,
            tokenDeviceId: _common_pb2.ResourceId | None = ...,
            enabled: _builtins.bool = ...,
            structureIds: _abc.Iterable[_common_pb2.ResourceId] | None = ...,
            label: _builtins.str = ...,
            metadata: Global___UserNFCTokenMetadataTrait.Metadata | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata", "tokenDeviceId", b"tokenDeviceId", "userId", b"userId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "label", b"label", "metadata", b"metadata", "structureIds", b"structureIds", "tokenDeviceId", b"tokenDeviceId", "userId", b"userId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    USERNFCTOKENS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def userNfcTokens(self) -> _containers.RepeatedCompositeFieldContainer[Global___UserNFCTokensTrait.UserNFCTokenData]: ...
    def __init__(
        self,
        *,
        userNfcTokens: _abc.Iterable[Global___UserNFCTokensTrait.UserNFCTokenData] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["userNfcTokens", b"userNfcTokens"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserNFCTokensTrait: _TypeAlias = UserNFCTokensTrait  # noqa: Y015

@_typing.final
class UserNFCTokenMetadataTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Metadata(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SERIALNUMBER_FIELD_NUMBER: _builtins.int
        TAGNUMBER_FIELD_NUMBER: _builtins.int
        serialNumber: _builtins.str
        tagNumber: _builtins.str
        def __init__(
            self,
            *,
            serialNumber: _builtins.str = ...,
            tagNumber: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["serialNumber", b"serialNumber", "tagNumber", b"tagNumber"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    METADATA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def metadata(self) -> Global___UserNFCTokenMetadataTrait.Metadata: ...
    def __init__(
        self,
        *,
        metadata: Global___UserNFCTokenMetadataTrait.Metadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserNFCTokenMetadataTrait: _TypeAlias = UserNFCTokenMetadataTrait  # noqa: Y015

@_typing.final
class BoltLockSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUTORELOCKON_FIELD_NUMBER: _builtins.int
    AUTORELOCKDURATION_FIELD_NUMBER: _builtins.int
    autoRelockOn: _builtins.bool
    @_builtins.property
    def autoRelockDuration(self) -> _duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        autoRelockOn: _builtins.bool = ...,
        autoRelockDuration: _duration_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["autoRelockDuration", b"autoRelockDuration"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["autoRelockDuration", b"autoRelockDuration", "autoRelockOn", b"autoRelockOn"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BoltLockSettingsTrait: _TypeAlias = BoltLockSettingsTrait  # noqa: Y015

@_typing.final
class BoltLockCapabilitiesTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _BoltLockCapabilitiesHandedness:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BoltLockCapabilitiesHandednessEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[BoltLockCapabilitiesTrait._BoltLockCapabilitiesHandedness.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        BOLT_LOCK_CAPABILITIES_HANDEDNESS_UNSPECIFIED: BoltLockCapabilitiesTrait._BoltLockCapabilitiesHandedness.ValueType  # 0
        BOLT_LOCK_CAPABILITIES_HANDEDNESS_RIGHT: BoltLockCapabilitiesTrait._BoltLockCapabilitiesHandedness.ValueType  # 1
        BOLT_LOCK_CAPABILITIES_HANDEDNESS_LEFT: BoltLockCapabilitiesTrait._BoltLockCapabilitiesHandedness.ValueType  # 2
        BOLT_LOCK_CAPABILITIES_HANDEDNESS_FIXED_UNKNOWN: BoltLockCapabilitiesTrait._BoltLockCapabilitiesHandedness.ValueType  # 3

    class BoltLockCapabilitiesHandedness(_BoltLockCapabilitiesHandedness, metaclass=_BoltLockCapabilitiesHandednessEnumTypeWrapper): ...
    BOLT_LOCK_CAPABILITIES_HANDEDNESS_UNSPECIFIED: BoltLockCapabilitiesTrait.BoltLockCapabilitiesHandedness.ValueType  # 0
    BOLT_LOCK_CAPABILITIES_HANDEDNESS_RIGHT: BoltLockCapabilitiesTrait.BoltLockCapabilitiesHandedness.ValueType  # 1
    BOLT_LOCK_CAPABILITIES_HANDEDNESS_LEFT: BoltLockCapabilitiesTrait.BoltLockCapabilitiesHandedness.ValueType  # 2
    BOLT_LOCK_CAPABILITIES_HANDEDNESS_FIXED_UNKNOWN: BoltLockCapabilitiesTrait.BoltLockCapabilitiesHandedness.ValueType  # 3

    HANDEDNESS_FIELD_NUMBER: _builtins.int
    MAXAUTORELOCKDURATION_FIELD_NUMBER: _builtins.int
    handedness: Global___BoltLockCapabilitiesTrait.BoltLockCapabilitiesHandedness.ValueType
    @_builtins.property
    def maxAutoRelockDuration(self) -> _duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        handedness: Global___BoltLockCapabilitiesTrait.BoltLockCapabilitiesHandedness.ValueType = ...,
        maxAutoRelockDuration: _duration_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["maxAutoRelockDuration", b"maxAutoRelockDuration"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["handedness", b"handedness", "maxAutoRelockDuration", b"maxAutoRelockDuration"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BoltLockCapabilitiesTrait: _TypeAlias = BoltLockCapabilitiesTrait  # noqa: Y015

@_typing.final
class UserNFCTokenSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class UserNfcTokensEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___UserNFCTokenSettingsTrait.UserNFCToken: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___UserNFCTokenSettingsTrait.UserNFCToken | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class UserNFCToken(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USERID_FIELD_NUMBER: _builtins.int
        TOKENDEVICEID_FIELD_NUMBER: _builtins.int
        PUBLICKEY_FIELD_NUMBER: _builtins.int
        publicKey: _builtins.bytes
        @_builtins.property
        def userId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def tokenDeviceId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            userId: _common_pb2.ResourceId | None = ...,
            tokenDeviceId: _common_pb2.ResourceId | None = ...,
            publicKey: _builtins.bytes = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["tokenDeviceId", b"tokenDeviceId", "userId", b"userId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["publicKey", b"publicKey", "tokenDeviceId", b"tokenDeviceId", "userId", b"userId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    USERNFCTOKENS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def userNfcTokens(self) -> _containers.MessageMap[_builtins.int, Global___UserNFCTokenSettingsTrait.UserNFCToken]: ...
    def __init__(
        self,
        *,
        userNfcTokens: _abc.Mapping[_builtins.int, Global___UserNFCTokenSettingsTrait.UserNFCToken] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["userNfcTokens", b"userNfcTokens"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserNFCTokenSettingsTrait: _TypeAlias = UserNFCTokenSettingsTrait  # noqa: Y015

@_typing.final
class DoorCheckSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DOORCHECKENABLED_FIELD_NUMBER: _builtins.int
    SENSORDEVICEID_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def doorCheckEnabled(self) -> _wrappers_pb2.BoolValue: ...
    @_builtins.property
    def sensorDeviceId(self) -> _common_pb2.ResourceId: ...
    def __init__(
        self,
        *,
        doorCheckEnabled: _wrappers_pb2.BoolValue | None = ...,
        sensorDeviceId: _common_pb2.ResourceId | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["doorCheckEnabled", b"doorCheckEnabled", "sensorDeviceId", b"sensorDeviceId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["doorCheckEnabled", b"doorCheckEnabled", "sensorDeviceId", b"sensorDeviceId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DoorCheckSettingsTrait: _TypeAlias = DoorCheckSettingsTrait  # noqa: Y015

@_typing.final
class PincodeInputSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WRONGENTRYCODELIMIT_FIELD_NUMBER: _builtins.int
    WRONGENTRYDISABLETIME_FIELD_NUMBER: _builtins.int
    wrongEntryCodeLimit: _builtins.int
    @_builtins.property
    def wrongEntryDisableTime(self) -> _duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        wrongEntryCodeLimit: _builtins.int = ...,
        wrongEntryDisableTime: _duration_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["wrongEntryDisableTime", b"wrongEntryDisableTime"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["wrongEntryCodeLimit", b"wrongEntryCodeLimit", "wrongEntryDisableTime", b"wrongEntryDisableTime"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PincodeInputSettingsTrait: _TypeAlias = PincodeInputSettingsTrait  # noqa: Y015

@_typing.final
class UserPincodesCapabilitiesTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MINPINCODELENGTH_FIELD_NUMBER: _builtins.int
    MAXPINCODELENGTH_FIELD_NUMBER: _builtins.int
    MAXPINCODESSUPPORTED_FIELD_NUMBER: _builtins.int
    minPincodeLength: _builtins.int
    maxPincodeLength: _builtins.int
    maxPincodesSupported: _builtins.int
    def __init__(
        self,
        *,
        minPincodeLength: _builtins.int = ...,
        maxPincodeLength: _builtins.int = ...,
        maxPincodesSupported: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["maxPincodeLength", b"maxPincodeLength", "maxPincodesSupported", b"maxPincodesSupported", "minPincodeLength", b"minPincodeLength"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserPincodesCapabilitiesTrait: _TypeAlias = UserPincodesCapabilitiesTrait  # noqa: Y015
