"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import any_pb2 as _any_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import field_mask_pb2 as _field_mask_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.rpc import status_pb2 as _status_pb2
from ...nest import messages_pb2 as _messages_pb2
import builtins as _builtins
import sys
import typing as _typing
from ... import wdl_event_importance_pb2 as _wdl_event_importance_pb2

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class TraitStateNotification(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _NotificationContext:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _NotificationContextEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TraitStateNotification._NotificationContext.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NOTIFICATION_CONTEXT_UNSPECIFIED: TraitStateNotification._NotificationContext.ValueType  # 0
        INITIAL_OBSERVE_RESPONSE: TraitStateNotification._NotificationContext.ValueType  # 1

    class NotificationContext(_NotificationContext, metaclass=_NotificationContextEnumTypeWrapper): ...
    NOTIFICATION_CONTEXT_UNSPECIFIED: TraitStateNotification.NotificationContext.ValueType  # 0
    INITIAL_OBSERVE_RESPONSE: TraitStateNotification.NotificationContext.ValueType  # 1

    STATE_FIELD_NUMBER: _builtins.int
    STATEMASK_FIELD_NUMBER: _builtins.int
    MONOTONICVERSION_FIELD_NUMBER: _builtins.int
    NOTIFICATIONCONTEXT_FIELD_NUMBER: _builtins.int
    PUBLISHERVERSION_FIELD_NUMBER: _builtins.int
    monotonicVersion: _builtins.int
    notificationContext: Global___TraitStateNotification.NotificationContext.ValueType
    publisherVersion: _builtins.int
    @_builtins.property
    def state(self) -> _any_pb2.Any: ...
    @_builtins.property
    def stateMask(self) -> _field_mask_pb2.FieldMask: ...
    def __init__(
        self,
        *,
        state: _any_pb2.Any | None = ...,
        stateMask: _field_mask_pb2.FieldMask | None = ...,
        monotonicVersion: _builtins.int = ...,
        notificationContext: Global___TraitStateNotification.NotificationContext.ValueType = ...,
        publisherVersion: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["state", b"state", "stateMask", b"stateMask"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["monotonicVersion", b"monotonicVersion", "notificationContext", b"notificationContext", "publisherVersion", b"publisherVersion", "state", b"state", "stateMask", b"stateMask"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitStateNotification: _TypeAlias = TraitStateNotification  # noqa: Y015

@_typing.final
class TraitEventsNotification(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EVENTS_FIELD_NUMBER: _builtins.int
    REQUESTUTCTIMESTAMP_FIELD_NUMBER: _builtins.int
    REQUESTSYSTEMTIMEOFFSETMILLIS_FIELD_NUMBER: _builtins.int
    SERVICERECEIVEDTIMESTAMP_FIELD_NUMBER: _builtins.int
    requestSystemTimeOffsetMillis: _builtins.int
    @_builtins.property
    def events(self) -> _containers.RepeatedCompositeFieldContainer[Global___Event]: ...
    @_builtins.property
    def requestUtcTimestamp(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def serviceReceivedTimestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        events: _abc.Iterable[Global___Event] | None = ...,
        requestUtcTimestamp: _timestamp_pb2.Timestamp | None = ...,
        requestSystemTimeOffsetMillis: _builtins.int = ...,
        serviceReceivedTimestamp: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["requestUtcTimestamp", b"requestUtcTimestamp", "serviceReceivedTimestamp", b"serviceReceivedTimestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["events", b"events", "requestSystemTimeOffsetMillis", b"requestSystemTimeOffsetMillis", "requestUtcTimestamp", b"requestUtcTimestamp", "serviceReceivedTimestamp", b"serviceReceivedTimestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitEventsNotification: _TypeAlias = TraitEventsNotification  # noqa: Y015

@_typing.final
class Event(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    IMPORTANCE_FIELD_NUMBER: _builtins.int
    EVENTID_FIELD_NUMBER: _builtins.int
    RELATEDEVENTIMPORTANCE_FIELD_NUMBER: _builtins.int
    RELATEDEVENTID_FIELD_NUMBER: _builtins.int
    UTCTIMESTAMP_FIELD_NUMBER: _builtins.int
    SYSTEMTIMEOFFSETMILLIS_FIELD_NUMBER: _builtins.int
    RELAYBYRESOURCEID_FIELD_NUMBER: _builtins.int
    SUBJECTRESOURCEID_FIELD_NUMBER: _builtins.int
    SUBJECTPAIRERID_FIELD_NUMBER: _builtins.int
    SUBJECTTYPENAME_FIELD_NUMBER: _builtins.int
    SUBJECTINSTANCEID_FIELD_NUMBER: _builtins.int
    SCHEMAVERSION_FIELD_NUMBER: _builtins.int
    importance: _wdl_event_importance_pb2.EventImportance.ValueType
    eventId: _builtins.int
    relatedEventImportance: _wdl_event_importance_pb2.EventImportance.ValueType
    relatedEventId: _builtins.int
    systemTimeOffsetMillis: _builtins.int
    relaybyResourceId: _builtins.str
    subjectResourceId: _builtins.str
    subjectPairerId: _builtins.str
    subjectTypeName: _builtins.str
    subjectInstanceId: _builtins.str
    @_builtins.property
    def data(self) -> _any_pb2.Any: ...
    @_builtins.property
    def utcTimestamp(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def schemaVersion(self) -> _messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        data: _any_pb2.Any | None = ...,
        importance: _wdl_event_importance_pb2.EventImportance.ValueType = ...,
        eventId: _builtins.int = ...,
        relatedEventImportance: _wdl_event_importance_pb2.EventImportance.ValueType = ...,
        relatedEventId: _builtins.int = ...,
        utcTimestamp: _timestamp_pb2.Timestamp | None = ...,
        systemTimeOffsetMillis: _builtins.int = ...,
        relaybyResourceId: _builtins.str = ...,
        subjectResourceId: _builtins.str = ...,
        subjectPairerId: _builtins.str = ...,
        subjectTypeName: _builtins.str = ...,
        subjectInstanceId: _builtins.str = ...,
        schemaVersion: _messages_pb2.SchemaVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "schemaVersion", b"schemaVersion", "utcTimestamp", b"utcTimestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "eventId", b"eventId", "importance", b"importance", "relatedEventId", b"relatedEventId", "relatedEventImportance", b"relatedEventImportance", "relaybyResourceId", b"relaybyResourceId", "schemaVersion", b"schemaVersion", "subjectInstanceId", b"subjectInstanceId", "subjectPairerId", b"subjectPairerId", "subjectResourceId", b"subjectResourceId", "subjectTypeName", b"subjectTypeName", "systemTimeOffsetMillis", b"systemTimeOffsetMillis", "utcTimestamp", b"utcTimestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Event: _TypeAlias = Event  # noqa: Y015

@_typing.final
class TraitRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: _builtins.int
    TRAITLABEL_FIELD_NUMBER: _builtins.int
    REQUESTID_FIELD_NUMBER: _builtins.int
    resourceId: _builtins.str
    traitLabel: _builtins.str
    requestId: _builtins.str
    def __init__(
        self,
        *,
        resourceId: _builtins.str = ...,
        traitLabel: _builtins.str = ...,
        requestId: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["requestId", b"requestId", "resourceId", b"resourceId", "traitLabel", b"traitLabel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitRequest: _TypeAlias = TraitRequest  # noqa: Y015

@_typing.final
class TraitOperation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _RequestCase:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _RequestCaseEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TraitOperation._RequestCase.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        REQUEST_NOT_SET: TraitOperation._RequestCase.ValueType  # 0
        COMMAND: TraitOperation._RequestCase.ValueType  # 6
        UPDATE: TraitOperation._RequestCase.ValueType  # 7

    class RequestCase(_RequestCase, metaclass=_RequestCaseEnumTypeWrapper): ...
    REQUEST_NOT_SET: TraitOperation.RequestCase.ValueType  # 0
    COMMAND: TraitOperation.RequestCase.ValueType  # 6
    UPDATE: TraitOperation.RequestCase.ValueType  # 7

    class _State:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TraitOperation._State.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATE_UNSPECIFIED: TraitOperation._State.ValueType  # 0
        QUEUED: TraitOperation._State.ValueType  # 1
        PENDING: TraitOperation._State.ValueType  # 2
        STARTED: TraitOperation._State.ValueType  # 3
        COMPLETE: TraitOperation._State.ValueType  # 4

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    STATE_UNSPECIFIED: TraitOperation.State.ValueType  # 0
    QUEUED: TraitOperation.State.ValueType  # 1
    PENDING: TraitOperation.State.ValueType  # 2
    STARTED: TraitOperation.State.ValueType  # 3
    COMPLETE: TraitOperation.State.ValueType  # 4

    TRAITREQUEST_FIELD_NUMBER: _builtins.int
    PROGRESS_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    EVENT_FIELD_NUMBER: _builtins.int
    PUBLISHERACCEPTEDSTATEVERSION_FIELD_NUMBER: _builtins.int
    COMMAND_FIELD_NUMBER: _builtins.int
    UPDATE_FIELD_NUMBER: _builtins.int
    progress: Global___TraitOperation.State.ValueType
    publisherAcceptedStateVersion: _builtins.int
    @_builtins.property
    def traitRequest(self) -> Global___TraitRequest: ...
    @_builtins.property
    def status(self) -> _status_pb2.Status: ...
    @_builtins.property
    def event(self) -> Global___TraitEvent: ...
    @_builtins.property
    def command(self) -> Global___TraitCommand: ...
    @_builtins.property
    def update(self) -> Global___TraitUpdateStateRequest: ...
    def __init__(
        self,
        *,
        traitRequest: Global___TraitRequest | None = ...,
        progress: Global___TraitOperation.State.ValueType = ...,
        status: _status_pb2.Status | None = ...,
        event: Global___TraitEvent | None = ...,
        publisherAcceptedStateVersion: _builtins.int = ...,
        command: Global___TraitCommand | None = ...,
        update: Global___TraitUpdateStateRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "event", b"event", "status", b"status", "traitRequest", b"traitRequest", "update", b"update"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "event", b"event", "progress", b"progress", "publisherAcceptedStateVersion", b"publisherAcceptedStateVersion", "status", b"status", "traitRequest", b"traitRequest", "update", b"update"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitOperation: _TypeAlias = TraitOperation  # noqa: Y015

@_typing.final
class TraitObserveRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: _builtins.int
    FIELDMASK_FIELD_NUMBER: _builtins.int
    MONOTONICVERSIONFILTER_FIELD_NUMBER: _builtins.int
    INCLUDECONFIRMEDSTATE_FIELD_NUMBER: _builtins.int
    INCLUDEPENDINGOPERATIONS_FIELD_NUMBER: _builtins.int
    monotonicVersionFilter: _builtins.int
    includeConfirmedState: _builtins.bool
    includePendingOperations: _builtins.bool
    @_builtins.property
    def traitRequest(self) -> Global___TraitRequest: ...
    @_builtins.property
    def fieldMask(self) -> _field_mask_pb2.FieldMask: ...
    def __init__(
        self,
        *,
        traitRequest: Global___TraitRequest | None = ...,
        fieldMask: _field_mask_pb2.FieldMask | None = ...,
        monotonicVersionFilter: _builtins.int = ...,
        includeConfirmedState: _builtins.bool = ...,
        includePendingOperations: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldMask", b"fieldMask", "traitRequest", b"traitRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldMask", b"fieldMask", "includeConfirmedState", b"includeConfirmedState", "includePendingOperations", b"includePendingOperations", "monotonicVersionFilter", b"monotonicVersionFilter", "traitRequest", b"traitRequest"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitObserveRequest: _TypeAlias = TraitObserveRequest  # noqa: Y015

@_typing.final
class TraitObserveResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: _builtins.int
    ACCEPTEDSTATE_FIELD_NUMBER: _builtins.int
    TRAITINFO_FIELD_NUMBER: _builtins.int
    CONFIRMEDSTATE_FIELD_NUMBER: _builtins.int
    PENDINGOPERATIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def traitRequest(self) -> Global___TraitRequest: ...
    @_builtins.property
    def acceptedState(self) -> Global___TraitStateNotification: ...
    @_builtins.property
    def traitInfo(self) -> Global___TraitInfo: ...
    @_builtins.property
    def confirmedState(self) -> Global___TraitStateNotification: ...
    @_builtins.property
    def pendingOperations(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraitOperation]: ...
    def __init__(
        self,
        *,
        traitRequest: Global___TraitRequest | None = ...,
        acceptedState: Global___TraitStateNotification | None = ...,
        traitInfo: Global___TraitInfo | None = ...,
        confirmedState: Global___TraitStateNotification | None = ...,
        pendingOperations: _abc.Iterable[Global___TraitOperation] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["acceptedState", b"acceptedState", "confirmedState", b"confirmedState", "traitInfo", b"traitInfo", "traitRequest", b"traitRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["acceptedState", b"acceptedState", "confirmedState", b"confirmedState", "pendingOperations", b"pendingOperations", "traitInfo", b"traitInfo", "traitRequest", b"traitRequest"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitObserveResponse: _TypeAlias = TraitObserveResponse  # noqa: Y015

@_typing.final
class TraitGetStateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: _builtins.int
    FIELDMASK_FIELD_NUMBER: _builtins.int
    MONOTONICVERSIONFILTER_FIELD_NUMBER: _builtins.int
    INCLUDECONFIRMEDSTATE_FIELD_NUMBER: _builtins.int
    INCLUDEPENDINGOPERATIONS_FIELD_NUMBER: _builtins.int
    monotonicVersionFilter: _builtins.int
    includeConfirmedState: _builtins.bool
    includePendingOperations: _builtins.bool
    @_builtins.property
    def traitRequest(self) -> Global___TraitRequest: ...
    @_builtins.property
    def fieldMask(self) -> _field_mask_pb2.FieldMask: ...
    def __init__(
        self,
        *,
        traitRequest: Global___TraitRequest | None = ...,
        fieldMask: _field_mask_pb2.FieldMask | None = ...,
        monotonicVersionFilter: _builtins.int = ...,
        includeConfirmedState: _builtins.bool = ...,
        includePendingOperations: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldMask", b"fieldMask", "traitRequest", b"traitRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldMask", b"fieldMask", "includeConfirmedState", b"includeConfirmedState", "includePendingOperations", b"includePendingOperations", "monotonicVersionFilter", b"monotonicVersionFilter", "traitRequest", b"traitRequest"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitGetStateRequest: _TypeAlias = TraitGetStateRequest  # noqa: Y015

@_typing.final
class TraitGetStateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: _builtins.int
    ACCEPTEDSTATE_FIELD_NUMBER: _builtins.int
    TRAITINFO_FIELD_NUMBER: _builtins.int
    CONFIRMEDSTATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def traitRequest(self) -> Global___TraitRequest: ...
    @_builtins.property
    def acceptedState(self) -> Global___TraitStateNotification: ...
    @_builtins.property
    def traitInfo(self) -> Global___TraitInfo: ...
    @_builtins.property
    def confirmedState(self) -> Global___TraitStateNotification: ...
    def __init__(
        self,
        *,
        traitRequest: Global___TraitRequest | None = ...,
        acceptedState: Global___TraitStateNotification | None = ...,
        traitInfo: Global___TraitInfo | None = ...,
        confirmedState: Global___TraitStateNotification | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["acceptedState", b"acceptedState", "confirmedState", b"confirmedState", "traitInfo", b"traitInfo", "traitRequest", b"traitRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["acceptedState", b"acceptedState", "confirmedState", b"confirmedState", "traitInfo", b"traitInfo", "traitRequest", b"traitRequest"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitGetStateResponse: _TypeAlias = TraitGetStateResponse  # noqa: Y015

@_typing.final
class TraitInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITTYPE_FIELD_NUMBER: _builtins.int
    SCHEMAVERSION_FIELD_NUMBER: _builtins.int
    traitType: _builtins.str
    @_builtins.property
    def schemaVersion(self) -> _messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        traitType: _builtins.str = ...,
        schemaVersion: _messages_pb2.SchemaVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schemaVersion", b"schemaVersion"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["schemaVersion", b"schemaVersion", "traitType", b"traitType"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitInfo: _TypeAlias = TraitInfo  # noqa: Y015

@_typing.final
class TraitUpdateStateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    STATEMASK_FIELD_NUMBER: _builtins.int
    MATCHPUBLISHERVERSION_FIELD_NUMBER: _builtins.int
    SCHEMAVERSION_FIELD_NUMBER: _builtins.int
    matchPublisherVersion: _builtins.int
    @_builtins.property
    def traitRequest(self) -> Global___TraitRequest: ...
    @_builtins.property
    def state(self) -> _any_pb2.Any: ...
    @_builtins.property
    def stateMask(self) -> _field_mask_pb2.FieldMask: ...
    @_builtins.property
    def schemaVersion(self) -> _messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        traitRequest: Global___TraitRequest | None = ...,
        state: _any_pb2.Any | None = ...,
        stateMask: _field_mask_pb2.FieldMask | None = ...,
        matchPublisherVersion: _builtins.int = ...,
        schemaVersion: _messages_pb2.SchemaVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schemaVersion", b"schemaVersion", "state", b"state", "stateMask", b"stateMask", "traitRequest", b"traitRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["matchPublisherVersion", b"matchPublisherVersion", "schemaVersion", b"schemaVersion", "state", b"state", "stateMask", b"stateMask", "traitRequest", b"traitRequest"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitUpdateStateRequest: _TypeAlias = TraitUpdateStateRequest  # noqa: Y015

@_typing.final
class TraitNotifyRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: _builtins.int
    CONFIRMEDSTATE_FIELD_NUMBER: _builtins.int
    EVENTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def traitRequest(self) -> Global___TraitRequest: ...
    @_builtins.property
    def confirmedState(self) -> Global___TraitStateNotification: ...
    @_builtins.property
    def events(self) -> Global___TraitEventsNotification: ...
    def __init__(
        self,
        *,
        traitRequest: Global___TraitRequest | None = ...,
        confirmedState: Global___TraitStateNotification | None = ...,
        events: Global___TraitEventsNotification | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["confirmedState", b"confirmedState", "events", b"events", "traitRequest", b"traitRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["confirmedState", b"confirmedState", "events", b"events", "traitRequest", b"traitRequest"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitNotifyRequest: _TypeAlias = TraitNotifyRequest  # noqa: Y015

@_typing.final
class TraitNotifyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def traitRequest(self) -> Global___TraitRequest: ...
    def __init__(
        self,
        *,
        traitRequest: Global___TraitRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["traitRequest", b"traitRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["traitRequest", b"traitRequest"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitNotifyResponse: _TypeAlias = TraitNotifyResponse  # noqa: Y015

@_typing.final
class TraitEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EVENT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def event(self) -> _any_pb2.Any: ...
    def __init__(
        self,
        *,
        event: _any_pb2.Any | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitEvent: _TypeAlias = TraitEvent  # noqa: Y015

@_typing.final
class TraitCommand(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: _builtins.int
    COMMAND_FIELD_NUMBER: _builtins.int
    EXPIRYTIME_FIELD_NUMBER: _builtins.int
    AUTHENTICATOR_FIELD_NUMBER: _builtins.int
    MATCHPUBLISHERVERSION_FIELD_NUMBER: _builtins.int
    SCHEMAVERSION_FIELD_NUMBER: _builtins.int
    NAMESPACEID_FIELD_NUMBER: _builtins.int
    authenticator: _builtins.bytes
    matchPublisherVersion: _builtins.int
    namespaceId: _builtins.str
    @_builtins.property
    def traitRequest(self) -> Global___TraitRequest: ...
    @_builtins.property
    def command(self) -> _any_pb2.Any: ...
    @_builtins.property
    def expiryTime(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def schemaVersion(self) -> _messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        traitRequest: Global___TraitRequest | None = ...,
        command: _any_pb2.Any | None = ...,
        expiryTime: _timestamp_pb2.Timestamp | None = ...,
        authenticator: _builtins.bytes = ...,
        matchPublisherVersion: _builtins.int = ...,
        schemaVersion: _messages_pb2.SchemaVersion | None = ...,
        namespaceId: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "expiryTime", b"expiryTime", "schemaVersion", b"schemaVersion", "traitRequest", b"traitRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authenticator", b"authenticator", "command", b"command", "expiryTime", b"expiryTime", "matchPublisherVersion", b"matchPublisherVersion", "namespaceId", b"namespaceId", "schemaVersion", b"schemaVersion", "traitRequest", b"traitRequest"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitCommand: _TypeAlias = TraitCommand  # noqa: Y015

@_typing.final
class WeaveStatusReport(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROFILEID_FIELD_NUMBER: _builtins.int
    STATUSCODE_FIELD_NUMBER: _builtins.int
    profileId: _builtins.int
    statusCode: _builtins.int
    def __init__(
        self,
        *,
        profileId: _builtins.int = ...,
        statusCode: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["profileId", b"profileId", "statusCode", b"statusCode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WeaveStatusReport: _TypeAlias = WeaveStatusReport  # noqa: Y015

@_typing.final
class ResourceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: _builtins.int
    REQUESTID_FIELD_NUMBER: _builtins.int
    NAMESPACEID_FIELD_NUMBER: _builtins.int
    resourceId: _builtins.str
    requestId: _builtins.str
    namespaceId: _builtins.str
    def __init__(
        self,
        *,
        resourceId: _builtins.str = ...,
        requestId: _builtins.str = ...,
        namespaceId: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["namespaceId", b"namespaceId", "requestId", b"requestId", "resourceId", b"resourceId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceRequest: _TypeAlias = ResourceRequest  # noqa: Y015

@_typing.final
class ResourceObserveRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: _builtins.int
    TRAITSTATEOBSERVES_FIELD_NUMBER: _builtins.int
    INCLUDECONFIRMEDSTATE_FIELD_NUMBER: _builtins.int
    INCLUDEPENDINGOPERATIONS_FIELD_NUMBER: _builtins.int
    includeConfirmedState: _builtins.bool
    includePendingOperations: _builtins.bool
    @_builtins.property
    def resourceRequest(self) -> Global___ResourceRequest: ...
    @_builtins.property
    def traitStateObserves(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraitStateObserve]: ...
    def __init__(
        self,
        *,
        resourceRequest: Global___ResourceRequest | None = ...,
        traitStateObserves: _abc.Iterable[Global___TraitStateObserve] | None = ...,
        includeConfirmedState: _builtins.bool = ...,
        includePendingOperations: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["resourceRequest", b"resourceRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["includeConfirmedState", b"includeConfirmedState", "includePendingOperations", b"includePendingOperations", "resourceRequest", b"resourceRequest", "traitStateObserves", b"traitStateObserves"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceObserveRequest: _TypeAlias = ResourceObserveRequest  # noqa: Y015

@_typing.final
class TraitStateObserve(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITLABEL_FIELD_NUMBER: _builtins.int
    FIELDMASK_FIELD_NUMBER: _builtins.int
    MONOTONICVERSIONFILTER_FIELD_NUMBER: _builtins.int
    traitLabel: _builtins.str
    monotonicVersionFilter: _builtins.int
    @_builtins.property
    def fieldMask(self) -> _field_mask_pb2.FieldMask: ...
    def __init__(
        self,
        *,
        traitLabel: _builtins.str = ...,
        fieldMask: _field_mask_pb2.FieldMask | None = ...,
        monotonicVersionFilter: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldMask", b"fieldMask"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldMask", b"fieldMask", "monotonicVersionFilter", b"monotonicVersionFilter", "traitLabel", b"traitLabel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitStateObserve: _TypeAlias = TraitStateObserve  # noqa: Y015

@_typing.final
class ResourceObserveResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: _builtins.int
    RESOURCEINFO_FIELD_NUMBER: _builtins.int
    TRAITRESPONSES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def resourceRequest(self) -> Global___ResourceRequest: ...
    @_builtins.property
    def resourceInfo(self) -> Global___ResourceInfo: ...
    @_builtins.property
    def traitResponses(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraitObserveResponse]: ...
    def __init__(
        self,
        *,
        resourceRequest: Global___ResourceRequest | None = ...,
        resourceInfo: Global___ResourceInfo | None = ...,
        traitResponses: _abc.Iterable[Global___TraitObserveResponse] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["resourceInfo", b"resourceInfo", "resourceRequest", b"resourceRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceInfo", b"resourceInfo", "resourceRequest", b"resourceRequest", "traitResponses", b"traitResponses"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceObserveResponse: _TypeAlias = ResourceObserveResponse  # noqa: Y015

@_typing.final
class ResourceInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TraitInfosEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___TraitInfo: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___TraitInfo | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    RESOURCETYPE_FIELD_NUMBER: _builtins.int
    TRAITINFOS_FIELD_NUMBER: _builtins.int
    IFACEINFOS_FIELD_NUMBER: _builtins.int
    CURRENTSCHEMAVERSION_FIELD_NUMBER: _builtins.int
    resourceType: _builtins.str
    currentSchemaVersion: _builtins.int
    @_builtins.property
    def traitInfos(self) -> _containers.MessageMap[_builtins.str, Global___TraitInfo]: ...
    @_builtins.property
    def ifaceInfos(self) -> _containers.RepeatedCompositeFieldContainer[Global___IfaceInfo]: ...
    def __init__(
        self,
        *,
        resourceType: _builtins.str = ...,
        traitInfos: _abc.Mapping[_builtins.str, Global___TraitInfo] | None = ...,
        ifaceInfos: _abc.Iterable[Global___IfaceInfo] | None = ...,
        currentSchemaVersion: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["currentSchemaVersion", b"currentSchemaVersion", "ifaceInfos", b"ifaceInfos", "resourceType", b"resourceType", "traitInfos", b"traitInfos"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceInfo: _TypeAlias = ResourceInfo  # noqa: Y015

@_typing.final
class IfaceInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IFACETYPE_FIELD_NUMBER: _builtins.int
    IFACETRAITINFOS_FIELD_NUMBER: _builtins.int
    SCHEMAVERSION_FIELD_NUMBER: _builtins.int
    ifaceType: _builtins.str
    @_builtins.property
    def ifaceTraitInfos(self) -> _containers.RepeatedCompositeFieldContainer[Global___IfaceTraitInfo]: ...
    @_builtins.property
    def schemaVersion(self) -> _messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        ifaceType: _builtins.str = ...,
        ifaceTraitInfos: _abc.Iterable[Global___IfaceTraitInfo] | None = ...,
        schemaVersion: _messages_pb2.SchemaVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schemaVersion", b"schemaVersion"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ifaceTraitInfos", b"ifaceTraitInfos", "ifaceType", b"ifaceType", "schemaVersion", b"schemaVersion"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IfaceInfo: _TypeAlias = IfaceInfo  # noqa: Y015

@_typing.final
class IfaceTraitInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IFACETRAITLABEL_FIELD_NUMBER: _builtins.int
    RESOURCETRAITLABEL_FIELD_NUMBER: _builtins.int
    ifaceTraitLabel: _builtins.str
    resourceTraitLabel: _builtins.str
    def __init__(
        self,
        *,
        ifaceTraitLabel: _builtins.str = ...,
        resourceTraitLabel: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ifaceTraitLabel", b"ifaceTraitLabel", "resourceTraitLabel", b"resourceTraitLabel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IfaceTraitInfo: _TypeAlias = IfaceTraitInfo  # noqa: Y015

@_typing.final
class ResourceGetStateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: _builtins.int
    RESOURCEGETSTATES_FIELD_NUMBER: _builtins.int
    INCLUDECONFIRMEDSTATE_FIELD_NUMBER: _builtins.int
    INCLUDEPENDINGOPERATIONS_FIELD_NUMBER: _builtins.int
    includeConfirmedState: _builtins.bool
    includePendingOperations: _builtins.bool
    @_builtins.property
    def resourceRequest(self) -> Global___ResourceRequest: ...
    @_builtins.property
    def resourceGetStates(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResourceGetState]: ...
    def __init__(
        self,
        *,
        resourceRequest: Global___ResourceRequest | None = ...,
        resourceGetStates: _abc.Iterable[Global___ResourceGetState] | None = ...,
        includeConfirmedState: _builtins.bool = ...,
        includePendingOperations: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["resourceRequest", b"resourceRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["includeConfirmedState", b"includeConfirmedState", "includePendingOperations", b"includePendingOperations", "resourceGetStates", b"resourceGetStates", "resourceRequest", b"resourceRequest"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceGetStateRequest: _TypeAlias = ResourceGetStateRequest  # noqa: Y015

@_typing.final
class ResourceGetState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITLABEL_FIELD_NUMBER: _builtins.int
    FIELDMASK_FIELD_NUMBER: _builtins.int
    MONOTONICVERSIONFILTER_FIELD_NUMBER: _builtins.int
    traitLabel: _builtins.str
    monotonicVersionFilter: _builtins.int
    @_builtins.property
    def fieldMask(self) -> _field_mask_pb2.FieldMask: ...
    def __init__(
        self,
        *,
        traitLabel: _builtins.str = ...,
        fieldMask: _field_mask_pb2.FieldMask | None = ...,
        monotonicVersionFilter: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fieldMask", b"fieldMask"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fieldMask", b"fieldMask", "monotonicVersionFilter", b"monotonicVersionFilter", "traitLabel", b"traitLabel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceGetState: _TypeAlias = ResourceGetState  # noqa: Y015

@_typing.final
class ResourceGetStateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: _builtins.int
    RESOURCEINFO_FIELD_NUMBER: _builtins.int
    TRAITRESPONSES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def resourceRequest(self) -> Global___ResourceRequest: ...
    @_builtins.property
    def resourceInfo(self) -> Global___ResourceInfo: ...
    @_builtins.property
    def traitResponses(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraitGetStateResponse]: ...
    def __init__(
        self,
        *,
        resourceRequest: Global___ResourceRequest | None = ...,
        resourceInfo: Global___ResourceInfo | None = ...,
        traitResponses: _abc.Iterable[Global___TraitGetStateResponse] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["resourceInfo", b"resourceInfo", "resourceRequest", b"resourceRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceInfo", b"resourceInfo", "resourceRequest", b"resourceRequest", "traitResponses", b"traitResponses"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceGetStateResponse: _TypeAlias = ResourceGetStateResponse  # noqa: Y015

@_typing.final
class ResourceNotifyRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: _builtins.int
    RESOURCESTATENOTIFIES_FIELD_NUMBER: _builtins.int
    RESOURCEEVENTSNOTIFIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def resourceRequest(self) -> Global___ResourceRequest: ...
    @_builtins.property
    def resourceStateNotifies(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResourceStateNotify]: ...
    @_builtins.property
    def resourceEventsNotifies(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResourceEventsNotify]: ...
    def __init__(
        self,
        *,
        resourceRequest: Global___ResourceRequest | None = ...,
        resourceStateNotifies: _abc.Iterable[Global___ResourceStateNotify] | None = ...,
        resourceEventsNotifies: _abc.Iterable[Global___ResourceEventsNotify] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["resourceRequest", b"resourceRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceEventsNotifies", b"resourceEventsNotifies", "resourceRequest", b"resourceRequest", "resourceStateNotifies", b"resourceStateNotifies"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceNotifyRequest: _TypeAlias = ResourceNotifyRequest  # noqa: Y015

@_typing.final
class ResourceStateNotify(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITLABEL_FIELD_NUMBER: _builtins.int
    CONFIRMEDSTATE_FIELD_NUMBER: _builtins.int
    traitLabel: _builtins.str
    @_builtins.property
    def confirmedState(self) -> Global___TraitStateNotification: ...
    def __init__(
        self,
        *,
        traitLabel: _builtins.str = ...,
        confirmedState: Global___TraitStateNotification | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["confirmedState", b"confirmedState"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["confirmedState", b"confirmedState", "traitLabel", b"traitLabel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceStateNotify: _TypeAlias = ResourceStateNotify  # noqa: Y015

@_typing.final
class ResourceEventsNotify(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITLABEL_FIELD_NUMBER: _builtins.int
    EVENTS_FIELD_NUMBER: _builtins.int
    traitLabel: _builtins.str
    @_builtins.property
    def events(self) -> Global___TraitEventsNotification: ...
    def __init__(
        self,
        *,
        traitLabel: _builtins.str = ...,
        events: Global___TraitEventsNotification | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["events", b"events"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["events", b"events", "traitLabel", b"traitLabel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceEventsNotify: _TypeAlias = ResourceEventsNotify  # noqa: Y015

@_typing.final
class ResourceNotifyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: _builtins.int
    TRAITRESPONSES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def resourceRequest(self) -> Global___ResourceRequest: ...
    @_builtins.property
    def traitResponses(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraitNotifyResponse]: ...
    def __init__(
        self,
        *,
        resourceRequest: Global___ResourceRequest | None = ...,
        traitResponses: _abc.Iterable[Global___TraitNotifyResponse] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["resourceRequest", b"resourceRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceRequest", b"resourceRequest", "traitResponses", b"traitResponses"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceNotifyResponse: _TypeAlias = ResourceNotifyResponse  # noqa: Y015

@_typing.final
class ResourceCommand(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITLABEL_FIELD_NUMBER: _builtins.int
    COMMAND_FIELD_NUMBER: _builtins.int
    EXPIRYTIME_FIELD_NUMBER: _builtins.int
    AUTHENTICATOR_FIELD_NUMBER: _builtins.int
    MATCHPUBLISHERVERSION_FIELD_NUMBER: _builtins.int
    SCHEMAVERSION_FIELD_NUMBER: _builtins.int
    RESOURCETYPE_FIELD_NUMBER: _builtins.int
    traitLabel: _builtins.str
    authenticator: _builtins.bytes
    matchPublisherVersion: _builtins.int
    resourceType: _builtins.str
    @_builtins.property
    def command(self) -> _any_pb2.Any: ...
    @_builtins.property
    def expiryTime(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def schemaVersion(self) -> _messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        traitLabel: _builtins.str = ...,
        command: _any_pb2.Any | None = ...,
        expiryTime: _timestamp_pb2.Timestamp | None = ...,
        authenticator: _builtins.bytes = ...,
        matchPublisherVersion: _builtins.int = ...,
        schemaVersion: _messages_pb2.SchemaVersion | None = ...,
        resourceType: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "expiryTime", b"expiryTime", "schemaVersion", b"schemaVersion"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authenticator", b"authenticator", "command", b"command", "expiryTime", b"expiryTime", "matchPublisherVersion", b"matchPublisherVersion", "resourceType", b"resourceType", "schemaVersion", b"schemaVersion", "traitLabel", b"traitLabel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceCommand: _TypeAlias = ResourceCommand  # noqa: Y015

@_typing.final
class SendCommandRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: _builtins.int
    RESOURCECOMMANDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def resourceRequest(self) -> Global___ResourceRequest: ...
    @_builtins.property
    def resourceCommands(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResourceCommand]: ...
    def __init__(
        self,
        *,
        resourceRequest: Global___ResourceRequest | None = ...,
        resourceCommands: _abc.Iterable[Global___ResourceCommand] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["resourceRequest", b"resourceRequest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceCommands", b"resourceCommands", "resourceRequest", b"resourceRequest"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SendCommandRequest: _TypeAlias = SendCommandRequest  # noqa: Y015

@_typing.final
class SendCommandResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ResourceCommandResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        RESOURCEREQUEST_FIELD_NUMBER: _builtins.int
        TRAITOPERATIONS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def resourceRequest(self) -> Global___ResourceRequest: ...
        @_builtins.property
        def traitOperations(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraitOperation]: ...
        def __init__(
            self,
            *,
            resourceRequest: Global___ResourceRequest | None = ...,
            traitOperations: _abc.Iterable[Global___TraitOperation] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["resourceRequest", b"resourceRequest"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceRequest", b"resourceRequest", "traitOperations", b"traitOperations"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SENDCOMMANDRESPONSE_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sendCommandResponse(self) -> _containers.RepeatedCompositeFieldContainer[Global___SendCommandResponse.ResourceCommandResponse]: ...
    @_builtins.property
    def status(self) -> _status_pb2.Status: ...
    def __init__(
        self,
        *,
        sendCommandResponse: _abc.Iterable[Global___SendCommandResponse.ResourceCommandResponse] | None = ...,
        status: _status_pb2.Status | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sendCommandResponse", b"sendCommandResponse", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SendCommandResponse: _TypeAlias = SendCommandResponse  # noqa: Y015

@_typing.final
class BatchUpdateStateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BATCHUPDATESTATEREQUEST_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def batchUpdateStateRequest(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraitUpdateStateRequest]: ...
    def __init__(
        self,
        *,
        batchUpdateStateRequest: _abc.Iterable[Global___TraitUpdateStateRequest] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["batchUpdateStateRequest", b"batchUpdateStateRequest"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BatchUpdateStateRequest: _TypeAlias = BatchUpdateStateRequest  # noqa: Y015

@_typing.final
class BatchUpdateStateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TraitOperationStateResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TRAITOPERATIONS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def traitOperations(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraitOperation]: ...
        def __init__(
            self,
            *,
            traitOperations: _abc.Iterable[Global___TraitOperation] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["traitOperations", b"traitOperations"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    BATCHUPDATESTATERESPONSE_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def batchUpdateStateResponse(self) -> _containers.RepeatedCompositeFieldContainer[Global___BatchUpdateStateResponse.TraitOperationStateResponse]: ...
    @_builtins.property
    def status(self) -> _status_pb2.Status: ...
    def __init__(
        self,
        *,
        batchUpdateStateResponse: _abc.Iterable[Global___BatchUpdateStateResponse.TraitOperationStateResponse] | None = ...,
        status: _status_pb2.Status | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["batchUpdateStateResponse", b"batchUpdateStateResponse", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BatchUpdateStateResponse: _TypeAlias = BatchUpdateStateResponse  # noqa: Y015
