"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import any_pb2 as _any_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import field_mask_pb2 as _field_mask_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from ...nest import messages_pb2 as _messages_pb2
from ...nestlabs.gateway import v1_pb2 as _v1_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _ResourceStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ResourceStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ResourceStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NORMAL: _ResourceStatus.ValueType  # 0
    ADDED: _ResourceStatus.ValueType  # 1
    REMOVED: _ResourceStatus.ValueType  # 2

class ResourceStatus(_ResourceStatus, metaclass=_ResourceStatusEnumTypeWrapper): ...

NORMAL: ResourceStatus.ValueType  # 0
ADDED: ResourceStatus.ValueType  # 1
REMOVED: ResourceStatus.ValueType  # 2
Global___ResourceStatus: _TypeAlias = ResourceStatus  # noqa: Y015

class _StateType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _StateTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_StateType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    STATE_TYPE_UNSPECIFIED: _StateType.ValueType  # 0
    CONFIRMED: _StateType.ValueType  # 1
    ACCEPTED: _StateType.ValueType  # 2

class StateType(_StateType, metaclass=_StateTypeEnumTypeWrapper): ...

STATE_TYPE_UNSPECIFIED: StateType.ValueType  # 0
CONFIRMED: StateType.ValueType  # 1
ACCEPTED: StateType.ValueType  # 2
Global___StateType: _TypeAlias = StateType  # noqa: Y015

@_typing.final
class TraitMeta(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITLABEL_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    SCHEMAVERSION_FIELD_NUMBER: _builtins.int
    traitLabel: _builtins.str
    type: _builtins.str
    @_builtins.property
    def schemaVersion(self) -> _messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        traitLabel: _builtins.str = ...,
        type: _builtins.str = ...,
        schemaVersion: _messages_pb2.SchemaVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schemaVersion", b"schemaVersion"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["schemaVersion", b"schemaVersion", "traitLabel", b"traitLabel", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitMeta: _TypeAlias = TraitMeta  # noqa: Y015

@_typing.final
class IfaceMeta(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TraitLabelMappingEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    IFACELABEL_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    TRAITLABELMAPPING_FIELD_NUMBER: _builtins.int
    SCHEMAVERSION_FIELD_NUMBER: _builtins.int
    ifaceLabel: _builtins.str
    type: _builtins.str
    @_builtins.property
    def traitLabelMapping(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def schemaVersion(self) -> _messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        ifaceLabel: _builtins.str = ...,
        type: _builtins.str = ...,
        traitLabelMapping: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        schemaVersion: _messages_pb2.SchemaVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schemaVersion", b"schemaVersion"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ifaceLabel", b"ifaceLabel", "schemaVersion", b"schemaVersion", "traitLabelMapping", b"traitLabelMapping", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IfaceMeta: _TypeAlias = IfaceMeta  # noqa: Y015

@_typing.final
class ResourceMeta(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    TRAITMETAS_FIELD_NUMBER: _builtins.int
    CURRENTSCHEMAVERSION_FIELD_NUMBER: _builtins.int
    IFACEMETAS_FIELD_NUMBER: _builtins.int
    resourceId: _builtins.str
    type: _builtins.str
    status: Global___ResourceStatus.ValueType
    currentSchemaVersion: _builtins.int
    @_builtins.property
    def traitMetas(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraitMeta]: ...
    @_builtins.property
    def ifaceMetas(self) -> _containers.RepeatedCompositeFieldContainer[Global___IfaceMeta]: ...
    def __init__(
        self,
        *,
        resourceId: _builtins.str = ...,
        type: _builtins.str = ...,
        status: Global___ResourceStatus.ValueType = ...,
        traitMetas: _abc.Iterable[Global___TraitMeta] | None = ...,
        currentSchemaVersion: _builtins.int = ...,
        ifaceMetas: _abc.Iterable[Global___IfaceMeta] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["currentSchemaVersion", b"currentSchemaVersion", "ifaceMetas", b"ifaceMetas", "resourceId", b"resourceId", "status", b"status", "traitMetas", b"traitMetas", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceMeta: _TypeAlias = ResourceMeta  # noqa: Y015

@_typing.final
class TraitId(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: _builtins.int
    TRAITLABEL_FIELD_NUMBER: _builtins.int
    resourceId: _builtins.str
    traitLabel: _builtins.str
    def __init__(
        self,
        *,
        resourceId: _builtins.str = ...,
        traitLabel: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId", "traitLabel", b"traitLabel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitId: _TypeAlias = TraitId  # noqa: Y015

@_typing.final
class Patch(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values(self) -> _any_pb2.Any: ...
    def __init__(
        self,
        *,
        values: _any_pb2.Any | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Patch: _TypeAlias = Patch  # noqa: Y015

@_typing.final
class TraitState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITID_FIELD_NUMBER: _builtins.int
    STATETYPES_FIELD_NUMBER: _builtins.int
    PATCH_FIELD_NUMBER: _builtins.int
    MONOTONICVERSION_FIELD_NUMBER: _builtins.int
    PUBLISHERVERSION_FIELD_NUMBER: _builtins.int
    monotonicVersion: _builtins.int
    publisherVersion: _builtins.int
    @_builtins.property
    def traitId(self) -> Global___TraitId: ...
    @_builtins.property
    def stateTypes(self) -> _containers.RepeatedScalarFieldContainer[Global___StateType.ValueType]: ...
    @_builtins.property
    def patch(self) -> Global___Patch: ...
    def __init__(
        self,
        *,
        traitId: Global___TraitId | None = ...,
        stateTypes: _abc.Iterable[Global___StateType.ValueType] | None = ...,
        patch: Global___Patch | None = ...,
        monotonicVersion: _builtins.int = ...,
        publisherVersion: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["patch", b"patch", "traitId", b"traitId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["monotonicVersion", b"monotonicVersion", "patch", b"patch", "publisherVersion", b"publisherVersion", "stateTypes", b"stateTypes", "traitId", b"traitId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitState: _TypeAlias = TraitState  # noqa: Y015

@_typing.final
class TraitTypeObserveParams(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITTYPE_FIELD_NUMBER: _builtins.int
    STATEFIELDMASK_FIELD_NUMBER: _builtins.int
    OBSERVERSCHEMAVERSION_FIELD_NUMBER: _builtins.int
    traitType: _builtins.str
    observerSchemaVersion: _builtins.int
    @_builtins.property
    def stateFieldMask(self) -> _field_mask_pb2.FieldMask: ...
    def __init__(
        self,
        *,
        traitType: _builtins.str = ...,
        stateFieldMask: _field_mask_pb2.FieldMask | None = ...,
        observerSchemaVersion: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stateFieldMask", b"stateFieldMask"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["observerSchemaVersion", b"observerSchemaVersion", "stateFieldMask", b"stateFieldMask", "traitType", b"traitType"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitTypeObserveParams: _TypeAlias = TraitTypeObserveParams  # noqa: Y015

@_typing.final
class TraitInstanceObserveParams(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITID_FIELD_NUMBER: _builtins.int
    MONOTONICVERSIONFILTERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def traitId(self) -> Global___TraitId: ...
    @_builtins.property
    def monotonicVersionFilters(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        traitId: Global___TraitId | None = ...,
        monotonicVersionFilters: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["traitId", b"traitId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["monotonicVersionFilters", b"monotonicVersionFilters", "traitId", b"traitId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitInstanceObserveParams: _TypeAlias = TraitInstanceObserveParams  # noqa: Y015

@_typing.final
class ObserveRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATETYPES_FIELD_NUMBER: _builtins.int
    RESOURCEIDS_FIELD_NUMBER: _builtins.int
    TRAITTYPEPARAMS_FIELD_NUMBER: _builtins.int
    TRAITINSTANCEPARAMS_FIELD_NUMBER: _builtins.int
    USERID_FIELD_NUMBER: _builtins.int
    userId: _builtins.str
    @_builtins.property
    def stateTypes(self) -> _containers.RepeatedScalarFieldContainer[Global___StateType.ValueType]: ...
    @_builtins.property
    def resourceIds(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def traitTypeParams(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraitTypeObserveParams]: ...
    @_builtins.property
    def traitInstanceParams(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraitInstanceObserveParams]: ...
    def __init__(
        self,
        *,
        stateTypes: _abc.Iterable[Global___StateType.ValueType] | None = ...,
        resourceIds: _abc.Iterable[_builtins.str] | None = ...,
        traitTypeParams: _abc.Iterable[Global___TraitTypeObserveParams] | None = ...,
        traitInstanceParams: _abc.Iterable[Global___TraitInstanceObserveParams] | None = ...,
        userId: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceIds", b"resourceIds", "stateTypes", b"stateTypes", "traitInstanceParams", b"traitInstanceParams", "traitTypeParams", b"traitTypeParams", "userId", b"userId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ObserveRequest: _TypeAlias = ObserveRequest  # noqa: Y015

@_typing.final
class TraitOperationList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITID_FIELD_NUMBER: _builtins.int
    TRAITOPERATIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def traitId(self) -> Global___TraitId: ...
    @_builtins.property
    def traitOperations(self) -> _containers.RepeatedCompositeFieldContainer[_v1_pb2.TraitOperation]: ...
    def __init__(
        self,
        *,
        traitId: Global___TraitId | None = ...,
        traitOperations: _abc.Iterable[_v1_pb2.TraitOperation] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["traitId", b"traitId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["traitId", b"traitId", "traitOperations", b"traitOperations"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitOperationList: _TypeAlias = TraitOperationList  # noqa: Y015

@_typing.final
class ObserveResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ObserveResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        RESOURCEMETAS_FIELD_NUMBER: _builtins.int
        INITIALRESOURCEMETASCONTINUE_FIELD_NUMBER: _builtins.int
        TRAITSTATES_FIELD_NUMBER: _builtins.int
        TRAITOPERATIONLISTS_FIELD_NUMBER: _builtins.int
        CURRENTTIME_FIELD_NUMBER: _builtins.int
        initialResourceMetasContinue: _builtins.bool
        @_builtins.property
        def resourceMetas(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResourceMeta]: ...
        @_builtins.property
        def traitStates(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraitState]: ...
        @_builtins.property
        def traitOperationLists(self) -> _containers.RepeatedCompositeFieldContainer[Global___TraitOperationList]: ...
        @_builtins.property
        def currentTime(self) -> _timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            resourceMetas: _abc.Iterable[Global___ResourceMeta] | None = ...,
            initialResourceMetasContinue: _builtins.bool = ...,
            traitStates: _abc.Iterable[Global___TraitState] | None = ...,
            traitOperationLists: _abc.Iterable[Global___TraitOperationList] | None = ...,
            currentTime: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["currentTime", b"currentTime"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["currentTime", b"currentTime", "initialResourceMetasContinue", b"initialResourceMetasContinue", "resourceMetas", b"resourceMetas", "traitOperationLists", b"traitOperationLists", "traitStates", b"traitStates"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    OBSERVERESPONSE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def observeResponse(self) -> _containers.RepeatedCompositeFieldContainer[Global___ObserveResponse.ObserveResponse]: ...
    def __init__(
        self,
        *,
        observeResponse: _abc.Iterable[Global___ObserveResponse.ObserveResponse] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["observeResponse", b"observeResponse"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ObserveResponse: _TypeAlias = ObserveResponse  # noqa: Y015
