"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing
from .. import wdl_event_importance_pb2 as _wdl_event_importance_pb2

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _DayOfWeek:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DayOfWeekEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DayOfWeek.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DAY_OF_WEEK_UNSPECIFIED: _DayOfWeek.ValueType  # 0
    DAY_OF_WEEK_SUNDAY: _DayOfWeek.ValueType  # 1
    DAY_OF_WEEK_MONDAY: _DayOfWeek.ValueType  # 2
    DAY_OF_WEEK_TUESDAY: _DayOfWeek.ValueType  # 4
    DAY_OF_WEEK_WEDNESDAY: _DayOfWeek.ValueType  # 8
    DAY_OF_WEEK_THURSDAY: _DayOfWeek.ValueType  # 16
    DAY_OF_WEEK_FRIDAY: _DayOfWeek.ValueType  # 32
    DAY_OF_WEEK_SATURDAY: _DayOfWeek.ValueType  # 64

class DayOfWeek(_DayOfWeek, metaclass=_DayOfWeekEnumTypeWrapper): ...

DAY_OF_WEEK_UNSPECIFIED: DayOfWeek.ValueType  # 0
DAY_OF_WEEK_SUNDAY: DayOfWeek.ValueType  # 1
DAY_OF_WEEK_MONDAY: DayOfWeek.ValueType  # 2
DAY_OF_WEEK_TUESDAY: DayOfWeek.ValueType  # 4
DAY_OF_WEEK_WEDNESDAY: DayOfWeek.ValueType  # 8
DAY_OF_WEEK_THURSDAY: DayOfWeek.ValueType  # 16
DAY_OF_WEEK_FRIDAY: DayOfWeek.ValueType  # 32
DAY_OF_WEEK_SATURDAY: DayOfWeek.ValueType  # 64
Global___DayOfWeek: _TypeAlias = DayOfWeek  # noqa: Y015

class _MonthOfYear:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MonthOfYearEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_MonthOfYear.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    MONTH_OF_YEAR_UNSPECIFIED: _MonthOfYear.ValueType  # 0
    MONTH_OF_YEAR_JANUARY: _MonthOfYear.ValueType  # 1
    MONTH_OF_YEAR_FEBRUARY: _MonthOfYear.ValueType  # 2
    MONTH_OF_YEAR_MARCH: _MonthOfYear.ValueType  # 4
    MONTH_OF_YEAR_APRIL: _MonthOfYear.ValueType  # 8
    MONTH_OF_YEAR_MAY: _MonthOfYear.ValueType  # 16
    MONTH_OF_YEAR_JUNE: _MonthOfYear.ValueType  # 32
    MONTH_OF_YEAR_JULY: _MonthOfYear.ValueType  # 64
    MONTH_OF_YEAR_AUGUST: _MonthOfYear.ValueType  # 128
    MONTH_OF_YEAR_SEPTEMBER: _MonthOfYear.ValueType  # 256
    MONTH_OF_YEAR_OCTOBER: _MonthOfYear.ValueType  # 512
    MONTH_OF_YEAR_NOVEMBER: _MonthOfYear.ValueType  # 1024
    MONTH_OF_YEAR_DECEMBER: _MonthOfYear.ValueType  # 2048

class MonthOfYear(_MonthOfYear, metaclass=_MonthOfYearEnumTypeWrapper): ...

MONTH_OF_YEAR_UNSPECIFIED: MonthOfYear.ValueType  # 0
MONTH_OF_YEAR_JANUARY: MonthOfYear.ValueType  # 1
MONTH_OF_YEAR_FEBRUARY: MonthOfYear.ValueType  # 2
MONTH_OF_YEAR_MARCH: MonthOfYear.ValueType  # 4
MONTH_OF_YEAR_APRIL: MonthOfYear.ValueType  # 8
MONTH_OF_YEAR_MAY: MonthOfYear.ValueType  # 16
MONTH_OF_YEAR_JUNE: MonthOfYear.ValueType  # 32
MONTH_OF_YEAR_JULY: MonthOfYear.ValueType  # 64
MONTH_OF_YEAR_AUGUST: MonthOfYear.ValueType  # 128
MONTH_OF_YEAR_SEPTEMBER: MonthOfYear.ValueType  # 256
MONTH_OF_YEAR_OCTOBER: MonthOfYear.ValueType  # 512
MONTH_OF_YEAR_NOVEMBER: MonthOfYear.ValueType  # 1024
MONTH_OF_YEAR_DECEMBER: MonthOfYear.ValueType  # 2048
Global___MonthOfYear: _TypeAlias = MonthOfYear  # noqa: Y015

class _ResourceType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ResourceTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ResourceType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RESOURCE_TYPE_UNSPECIFIED: _ResourceType.ValueType  # 0
    RESOURCE_TYPE_DEVICE: _ResourceType.ValueType  # 1
    RESOURCE_TYPE_USER: _ResourceType.ValueType  # 2
    RESOURCE_TYPE_ACCOUNT: _ResourceType.ValueType  # 3
    RESOURCE_TYPE_AREA: _ResourceType.ValueType  # 4
    RESOURCE_TYPE_FIXTURE: _ResourceType.ValueType  # 5
    RESOURCE_TYPE_GROUP: _ResourceType.ValueType  # 6
    RESOURCE_TYPE_ANNOTATION: _ResourceType.ValueType  # 7
    RESOURCE_TYPE_STRUCTURE: _ResourceType.ValueType  # 8
    RESOURCE_TYPE_GUEST: _ResourceType.ValueType  # 9
    RESOURCE_TYPE_SERVICE: _ResourceType.ValueType  # 10

class ResourceType(_ResourceType, metaclass=_ResourceTypeEnumTypeWrapper): ...

RESOURCE_TYPE_UNSPECIFIED: ResourceType.ValueType  # 0
RESOURCE_TYPE_DEVICE: ResourceType.ValueType  # 1
RESOURCE_TYPE_USER: ResourceType.ValueType  # 2
RESOURCE_TYPE_ACCOUNT: ResourceType.ValueType  # 3
RESOURCE_TYPE_AREA: ResourceType.ValueType  # 4
RESOURCE_TYPE_FIXTURE: ResourceType.ValueType  # 5
RESOURCE_TYPE_GROUP: ResourceType.ValueType  # 6
RESOURCE_TYPE_ANNOTATION: ResourceType.ValueType  # 7
RESOURCE_TYPE_STRUCTURE: ResourceType.ValueType  # 8
RESOURCE_TYPE_GUEST: ResourceType.ValueType  # 9
RESOURCE_TYPE_SERVICE: ResourceType.ValueType  # 10
Global___ResourceType: _TypeAlias = ResourceType  # noqa: Y015

class _QuantityType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _QuantityTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_QuantityType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    QUANTITY_TYPE_UNSPECIFIED: _QuantityType.ValueType  # 0
    LENGTH: _QuantityType.ValueType  # 1
    MASS: _QuantityType.ValueType  # 2
    DURATION: _QuantityType.ValueType  # 3
    CURRENT: _QuantityType.ValueType  # 4
    TEMPERATURE: _QuantityType.ValueType  # 5
    LUMINOUS_INTENSITY: _QuantityType.ValueType  # 6
    AREA: _QuantityType.ValueType  # 7
    VOLUME: _QuantityType.ValueType  # 8
    VELOCITY: _QuantityType.ValueType  # 9
    ACCELERATION: _QuantityType.ValueType  # 10
    FREQUENCY: _QuantityType.ValueType  # 27
    ENERGY: _QuantityType.ValueType  # 30
    ELECTRIC_CHARGE: _QuantityType.ValueType  # 32
    VOLTAGE: _QuantityType.ValueType  # 33
    RESISTANCE: _QuantityType.ValueType  # 34
    MAGNETIC_FLUX_DENSITY: _QuantityType.ValueType  # 38
    ILLUMINANCE: _QuantityType.ValueType  # 42
    HUMIDITY: _QuantityType.ValueType  # 46
    DBM: _QuantityType.ValueType  # 47
    PPM: _QuantityType.ValueType  # 48
    PIRMEASUREMENT: _QuantityType.ValueType  # 256
    NORMALIZED: _QuantityType.ValueType  # 257
    ANGLE: _QuantityType.ValueType  # 259

class QuantityType(_QuantityType, metaclass=_QuantityTypeEnumTypeWrapper): ...

QUANTITY_TYPE_UNSPECIFIED: QuantityType.ValueType  # 0
LENGTH: QuantityType.ValueType  # 1
MASS: QuantityType.ValueType  # 2
DURATION: QuantityType.ValueType  # 3
CURRENT: QuantityType.ValueType  # 4
TEMPERATURE: QuantityType.ValueType  # 5
LUMINOUS_INTENSITY: QuantityType.ValueType  # 6
AREA: QuantityType.ValueType  # 7
VOLUME: QuantityType.ValueType  # 8
VELOCITY: QuantityType.ValueType  # 9
ACCELERATION: QuantityType.ValueType  # 10
FREQUENCY: QuantityType.ValueType  # 27
ENERGY: QuantityType.ValueType  # 30
ELECTRIC_CHARGE: QuantityType.ValueType  # 32
VOLTAGE: QuantityType.ValueType  # 33
RESISTANCE: QuantityType.ValueType  # 34
MAGNETIC_FLUX_DENSITY: QuantityType.ValueType  # 38
ILLUMINANCE: QuantityType.ValueType  # 42
HUMIDITY: QuantityType.ValueType  # 46
DBM: QuantityType.ValueType  # 47
PPM: QuantityType.ValueType  # 48
PIRMEASUREMENT: QuantityType.ValueType  # 256
NORMALIZED: QuantityType.ValueType  # 257
ANGLE: QuantityType.ValueType  # 259
Global___QuantityType: _TypeAlias = QuantityType  # noqa: Y015

@_typing.final
class ResourceId(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: _builtins.int
    resourceId: _builtins.str
    def __init__(
        self,
        *,
        resourceId: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceId: _TypeAlias = ResourceId  # noqa: Y015

@_typing.final
class ResourceName(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCENAME_FIELD_NUMBER: _builtins.int
    resourceName: _builtins.str
    def __init__(
        self,
        *,
        resourceName: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceName", b"resourceName"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResourceName: _TypeAlias = ResourceName  # noqa: Y015

@_typing.final
class TraitTypeId(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITTYPEID_FIELD_NUMBER: _builtins.int
    traitTypeId: _builtins.int
    def __init__(
        self,
        *,
        traitTypeId: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["traitTypeId", b"traitTypeId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitTypeId: _TypeAlias = TraitTypeId  # noqa: Y015

@_typing.final
class TraitTypeInstance(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRAITTYPEID_FIELD_NUMBER: _builtins.int
    INSTANCEID_FIELD_NUMBER: _builtins.int
    instanceId: _builtins.int
    @_builtins.property
    def traitTypeId(self) -> Global___TraitTypeId: ...
    def __init__(
        self,
        *,
        traitTypeId: Global___TraitTypeId | None = ...,
        instanceId: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["traitTypeId", b"traitTypeId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["instanceId", b"instanceId", "traitTypeId", b"traitTypeId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitTypeInstance: _TypeAlias = TraitTypeInstance  # noqa: Y015

@_typing.final
class TraitInstanceId(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _TraitInstanceCase:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TraitInstanceCaseEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TraitInstanceId._TraitInstanceCase.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        TRAIT_INSTANCE_NOT_SET: TraitInstanceId._TraitInstanceCase.ValueType  # 0
        TRAIT_INSTANCE_LABEL: TraitInstanceId._TraitInstanceCase.ValueType  # 1
        TRAIT_INSTANCE_ID: TraitInstanceId._TraitInstanceCase.ValueType  # 2

    class TraitInstanceCase(_TraitInstanceCase, metaclass=_TraitInstanceCaseEnumTypeWrapper): ...
    TRAIT_INSTANCE_NOT_SET: TraitInstanceId.TraitInstanceCase.ValueType  # 0
    TRAIT_INSTANCE_LABEL: TraitInstanceId.TraitInstanceCase.ValueType  # 1
    TRAIT_INSTANCE_ID: TraitInstanceId.TraitInstanceCase.ValueType  # 2

    TRAITINSTANCELABEL_FIELD_NUMBER: _builtins.int
    TRAITINSTANCEID_FIELD_NUMBER: _builtins.int
    traitInstanceLabel: _builtins.str
    @_builtins.property
    def traitInstanceId(self) -> Global___TraitTypeInstance: ...
    def __init__(
        self,
        *,
        traitInstanceLabel: _builtins.str = ...,
        traitInstanceId: Global___TraitTypeInstance | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["traitInstanceId", b"traitInstanceId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["traitInstanceId", b"traitInstanceId", "traitInstanceLabel", b"traitInstanceLabel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TraitInstanceId: _TypeAlias = TraitInstanceId  # noqa: Y015

@_typing.final
class FullTraitInstanceId(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: _builtins.int
    TRAITINSTANCEID_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def resourceId(self) -> Global___ResourceId: ...
    @_builtins.property
    def traitInstanceId(self) -> Global___TraitInstanceId: ...
    def __init__(
        self,
        *,
        resourceId: Global___ResourceId | None = ...,
        traitInstanceId: Global___TraitInstanceId | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId", "traitInstanceId", b"traitInstanceId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId", "traitInstanceId", b"traitInstanceId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FullTraitInstanceId: _TypeAlias = FullTraitInstanceId  # noqa: Y015

@_typing.final
class InterfaceName(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INTERFACENAME_FIELD_NUMBER: _builtins.int
    interfaceName: _builtins.str
    def __init__(
        self,
        *,
        interfaceName: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["interfaceName", b"interfaceName"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___InterfaceName: _TypeAlias = InterfaceName  # noqa: Y015

@_typing.final
class EventId(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: _builtins.int
    IMPORTANCE_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    importance: _wdl_event_importance_pb2.EventImportance.ValueType
    id: _builtins.int
    @_builtins.property
    def resourceId(self) -> Global___ResourceId: ...
    def __init__(
        self,
        *,
        resourceId: Global___ResourceId | None = ...,
        importance: _wdl_event_importance_pb2.EventImportance.ValueType = ...,
        id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "importance", b"importance", "resourceId", b"resourceId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventId: _TypeAlias = EventId  # noqa: Y015

@_typing.final
class ProfileSpecificStatusCode(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROFILEID_FIELD_NUMBER: _builtins.int
    STATUSCODE_FIELD_NUMBER: _builtins.int
    profileId: _builtins.int
    statusCode: _builtins.int
    def __init__(
        self,
        *,
        profileId: _builtins.int = ...,
        statusCode: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["profileId", b"profileId", "statusCode", b"statusCode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProfileSpecificStatusCode: _TypeAlias = ProfileSpecificStatusCode  # noqa: Y015

@_typing.final
class StringRef(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _StringRefCase:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StringRefCaseEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StringRef._StringRefCase.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STRING_REF_NOT_SET: StringRef._StringRefCase.ValueType  # 0
        LITERAL: StringRef._StringRefCase.ValueType  # 1
        REFERENCE: StringRef._StringRefCase.ValueType  # 2

    class StringRefCase(_StringRefCase, metaclass=_StringRefCaseEnumTypeWrapper): ...
    STRING_REF_NOT_SET: StringRef.StringRefCase.ValueType  # 0
    LITERAL: StringRef.StringRefCase.ValueType  # 1
    REFERENCE: StringRef.StringRefCase.ValueType  # 2

    LITERAL_FIELD_NUMBER: _builtins.int
    REFERENCE_FIELD_NUMBER: _builtins.int
    literal: _builtins.str
    reference: _builtins.int
    def __init__(
        self,
        *,
        literal: _builtins.str = ...,
        reference: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["literal", b"literal", "reference", b"reference"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StringRef: _TypeAlias = StringRef  # noqa: Y015

@_typing.final
class Timer(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIME_FIELD_NUMBER: _builtins.int
    TIMEBASIS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def time(self) -> _duration_pb2.Duration: ...
    @_builtins.property
    def timeBasis(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        time: _duration_pb2.Duration | None = ...,
        timeBasis: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["time", b"time", "timeBasis", b"timeBasis"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["time", b"time", "timeBasis", b"timeBasis"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Timer: _TypeAlias = Timer  # noqa: Y015

@_typing.final
class TimeOfDay(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HOUR_FIELD_NUMBER: _builtins.int
    MINUTE_FIELD_NUMBER: _builtins.int
    SECOND_FIELD_NUMBER: _builtins.int
    hour: _builtins.int
    minute: _builtins.int
    second: _builtins.int
    def __init__(
        self,
        *,
        hour: _builtins.int = ...,
        minute: _builtins.int = ...,
        second: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hour", b"hour", "minute", b"minute", "second", b"second"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TimeOfDay: _TypeAlias = TimeOfDay  # noqa: Y015
