name: Validate with hassfest

on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - name: Remove non-integration manifest files
        run: rm -rf chrome-extension
      - uses: home-assistant/actions/hassfest@master
