name: Validate with hassfest

on: 
  schedule: 
    - cron: '0 0 * * *'
  pull_request:

jobs: 
  validate: 
    runs-on: "ubuntu-latest"
    steps: 
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master
